



*


pkg install

 sudo pkg install sourcecodepro-ttf ## 융통성없는 검색이므로 한자라도 틀리면 안됨.
** font for spacemacs default
$ sudo pkg install sourcecodepro-ttf
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        sourcecodepro-ttf: 2.030_1

Number of packages to be installed: 1

The process will require 3 MiB more space.
587 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching sourcecodepro-ttf-2.030_1.txz: 100%  587 KiB  50.1kB/s    00:12    
Checking integrity... done (0 conflicting)
[1/1] Installing sourcecodepro-ttf-2.030_1...
[1/1] Extracting sourcecodepro-ttf-2.030_1: 100%
=====
Message from sourcecodepro-ttf-2.030_1:

--
You can start using the fonts by following these instructions:

Add the following line to the "Files" section of your x.org configuration file:

        FontPath "/usr/local/share/fonts/SourceCodePro/"
# 파일 위치를 기억해서 파일구조를 염탐할 것.

