;; 이 파일의 설정목적:
   - 유튜브의 파일을 incoginto로 열어서 기록이 남는 번거로움을 줄인다.
   - brave://로 시작하는 url을 열어내는 것을 특정함
[[incognito_browser][How do I open Chromium in incognito mode by default? - Ask Ubuntu]] 다양한 방법을 보여줌. [[incognito_browser]]

M-x ffap (click on a link or Alt+x find-file-at-point (alias ffap))
#+BEGIN_SRC emacs-lisp
;; 출처: [[http://ergoemacs.org/emacs/emacs_set_default_browser.html][Emacs: Set Default Browser]]
;; set specific browser to open links
(setq browse-url-browser-function 'browse-url-firefox)
(setq browse-url-browser-function 'browse-url-chromium) ; google's browser
(setq browse-url-browser-function 'eww-browse-url) ; emacs browser
;;;; You can also set up a regex list to open specific browser depending on URL.

;; use browser depending on url
(setq
 browse-url-browser-function
 '(
  ("wikipedia\\.org" . browse-url-firefox)
  ("github" . browse-url-chromium)
  ("thefreedictionary\\.com" . eww-browse-url)
  ("." . browse-url-default-browser)
  ))
#+END_SRC

browse-url-xdg-open

browse-url-browser-function ;; C-x C-e => browse-url-default-browser

- 일단 환경변수 설정하는 법을 발견함. 그리고 자신의 함수를 만드는 법을 발견함
#+BEGIN_SRC emacs-lisp
;; 출처: [[http://ergoemacs.org/emacs/elisp_browse_url.html][Elisp: View URL in Web Browser: browse-url]]
(defun my-browse-url-of-buffer-with-firefox ()
  "Same as `browse-url-of-buffer' but using Firefox.
You need Firefox's path in the path environment variable within emacs.
e.g.
 (setenv \"PATH\" (concat \"C:/Program Files (x86)/Mozilla Firefox/\" \";\" (getenv \"PATH\") ) )
On Mac OS X, you don't need to. This command makes this shell call:
 「open -a Firefox.app http://example.com/」"
  (interactive)
  (cond ;;operation system OS운영체계에 따라서 string을 다르게 변성하는 법을 고안함.
   ((string-equal system-type "windows-nt") ; Windows
    (shell-command (concat "firefox file://" buffer-file-name)))
   ((string-equal system-type "gnu/linux")
    (shell-command (concat "firefox file://" buffer-file-name)))
   ((string-equal system-type "darwin") ; Mac
    (shell-command (concat "open -a Firefox.app file://" buffer-file-name)))))

;; set env var named “path” by appending a new path
(setenv "PATH"
        (concat
         "C:/Program Files (x86)/Mozilla Firefox/"
         ";"
         (getenv "PATH")))

#+END_SRC


* 정식의 사이트설명서 중요함 : 출처 [[https://www.emacswiki.org/emacs/BrowseUrl][EmacsWiki: Browse Url]]
각종 명령양식이 많아서 검토가 필요함.



* incognito_browser
다양한 방법을 보여줌. [[incognito_browser]] 
[[https://askubuntu.com/questions/461943/how-do-i-open-chromium-in-incognito-mode-by-default][How do I open Chromium in incognito mode by default? - Ask Ubuntu]] 다양한 방법을 보여줌.
- 아에 무기명의 브라우져오픈을 디폴트로 해서 적체를 방지하는 것도 중요한 방침일 것이다!!!


You have to change one line in the chromium-browser.desktop file. The best is to do that locally:

Copy the file from /usr/share/applications to /home/yourname/.local/share/applications
Open the file with gedit (open gedit and drag the local desktop file on to the gedit window)
Find the first line in the file that begins with Exec=
Replace the line by Exec=chromium-browser --incognito
a few remarks:


Run sudo update-alternatives --config x-www-browser and select /usr/bin/chromium-browser. This will make Chromium your system's default browser.
Run sudo -e /etc/chromium-browser/default (edit as root), and change the line that reads CHROMIUM_FLAGS="" to CHROMIUM_FLAGS="--incognito".
