;; 이 파일의 설정목적:
   - 유튜브의 파일을 incoginto로 열어서 기록이 남는 번거로움을 줄인다.
   - brave://로 시작하는 url을 열어내는 것을 특정함
[[incognito_browser][How do I open Chromium in incognito mode by default? - Ask Ubuntu]] 다양한 방법을 보여줌. [[incognito_browser]]


help:finder-commentary ; file:../../app/emacs/finder.org
; 패키의 주석문을 볼 수 있어서 각 개요을 잡는데 큰 도움을 준다. browse_url_browser_function.org 보다가 발견함
help:browse-url 에서 _'browse-url.el'_ 을 클릭해서 우연히 발견함! 
(finder-commentary "browse-url.el") help:finder-commentary




<f11>
help:toggle-frame-fullscreen toggle-frame-fullscreen
(toggle-frame-fullscreen)


<M-f10>, ESC <f10>
help:toggle-frame-maximized (toggle-frame-maximized)


finder-
finder-

M-x ffap (click on a link or Alt+x find-file-at-point (alias ffap))
#+BEGIN_SRC emacs-lisp
;; 출처: [[http://ergoemacs.org/emacs/emacs_set_default_browser.html][Emacs: Set Default Browser]]
;; set specific browser to open links
(setq browse-url-browser-function 'browse-url-firefox)
(setq browse-url-browser-function 'browse-url-chromium) ; google's browser
(setq browse-url-browser-function 'eww-browse-url) ; emacs browser
;;;; You can also set up a regex list to open specific browser depending on URL.
(executable-find "espeak")
;; 
;; use browser depending on url
(setq
 browse-url-browser-function
 '(
  ("wikipedia\\.org" . browse-url-firefox)
  ("github" . browse-url-chromium)
  ("thefreedictionary\\.com" . eww-browse-url)
  ("." . browse-url-default-browser)
  ))
#+END_SRC

browse-url-xdg-open

browse-url-browser-function ;; C-x C-e => browse-url-default-browser

- 일단 환경변수 설정하는 법을 발견함. 그리고 자신의 함수를 만드는 법을 발견함
#+BEGIN_SRC emacs-lisp
;; 출처: [[http://ergoemacs.org/emacs/elisp_browse_url.html][Elisp: View URL in Web Browser: browse-url]]
(defun my-browse-url-of-buffer-with-firefox ()
  "Same as `browse-url-of-buffer' but using Firefox.
You need Firefox's path in the path environment variable within emacs.
e.g.
 (setenv \"PATH\" (concat \"C:/Program Files (x86)/Mozilla Firefox/\" \";\" (getenv \"PATH\") ) )
On Mac OS X, you don't need to. This command makes this shell call:
 「open -a Firefox.app http://example.com/」"
  (interactive)
  (cond ;;operation system OS운영체계에 따라서 string을 다르게 변성하는 법을 고안함.
   ((string-equal system-type "windows-nt") ; Windows
    (shell-command (concat "firefox file://" buffer-file-name)))
   ((string-equal system-type "gnu/linux")
    (shell-command (concat "firefox file://" buffer-file-name)))
   ((string-equal system-type "darwin") ; Mac
    (shell-command (concat "open -a Firefox.app file://" buffer-file-name)))))

;; set env var named “path” by appending a new path
(setenv "PATH"
        (concat
         "C:/Program Files (x86)/Mozilla Firefox/"
         ";"
         (getenv "PATH")))

#+END_SRC


* 정식의 사이트설명서 중요함 : 출처 [[https://www.emacswiki.org/emacs/BrowseUrl][EmacsWiki: Browse Url]]
각종 명령양식이 많아서 검토가 필요함.



* incognito_browser
다양한 방법을 보여줌. [[incognito_browser]] 
[[https://askubuntu.com/questions/461943/how-do-i-open-chromium-in-incognito-mode-by-default][How do I open Chromium in incognito mode by default? - Ask Ubuntu]] 다양한 방법을 보여줌.
- 아에 무기명의 브라우져오픈을 디폴트로 해서 적체를 방지하는 것도 중요한 방침일 것이다!!!


You have to change one line in the chromium-browser.desktop file. The best is to do that locally:

Copy the file from /usr/share/applications to /home/yourname/.local/share/applications
Open the file with gedit (open gedit and drag the local desktop file on to the gedit window)
Find the first line in the file that begins with Exec=
Replace the line by Exec=chromium-browser --incognito
a few remarks:


Run sudo update-alternatives --config x-www-browser and select /usr/bin/chromium-browser. This will make Chromium your system's default browser.
Run sudo -e /etc/chromium-browser/default (edit as root), and change the line that reads CHROMIUM_FLAGS="" to CHROMIUM_FLAGS="--incognito".

* browse-url-generic-program

[[https://blog.binchen.org/posts/open-url-in-emacs-with-external-browser.html][Open url in Emacs with external browser | Chen's blog]]
#+begin_src emacs-lisp :results silent
defun w3mext-open-link-or-image-or-url ()
  "Opens the current link or image or current page's uri or any url-like text under cursor in firefox."
  (interactive)
  (let (url)
    (if (string= major-mode "w3m-mode")
        (setq url (or (w3m-anchor) (w3m-image) w3m-current-url)))
    (browse-url-generic (if url url (car (browse-url-interactive-arg "URL: "))))
    ))
(global-set-key (kbd "C-c b") 'w3mext-open-link-or-image-or-url)

;; 
C-h v browse-url-generic-program RET
 to see the documentation
;; is-a-mac and linux is the boolean constants defined by me


(setq browse-url-generic-program
      (cond
       (is-a-mac "open")
       (linux (executable-find "firefox"))
       ))



#+end_src

[[https://www.emacswiki.org/emacs/BrowseUrl][EmacsWiki: Browse Url]]
app/
help:browse-url-generic
help:browse-url-generic-program

(setq browse-url-browser-function 'browse-url-generic
         browse-url-generic-program "/path/to/conkeror")
#+begin_src sh :results silent
espeak -a 20 -v other/la "amare"
#+end_src

