* diff-mode 에 관하여 
dired에서 = 키를 눌러서 실행함!
활용처: 파일의 비교에 사용하기 편할 것임. ediff와 비교 바람.



Diff mode defined in ‘diff-mode.el’:
Major mode for viewing/editing context diffs.
Supports unified and context diffs as well as (to a lesser extent)
normal diffs.

When the buffer is read-only, the ESC prefix is not necessary.
If you edit the buffer manually, diff-mode will try to update the hunk
headers for you on-the-fly.

You can also switch between context diff and unified diff with C-c C-u,
or vice versa with C-c C-d and you can also reverse the direction of
a diff with R.

   key             binding
---             -------

C-c		Prefix Command
C-x		Prefix Command
ESC		Prefix Command

C-x 4		Prefix Command

C-c C-a		diff-apply-hunk
C-c C-b		diff-refine-hunk
C-c C-c		diff-goto-source
C-c C-d		diff-unified->context
C-c C-e		diff-ediff-patch
C-c C-f		next-error-follow-minor-mode
C-c C-n		diff-restrict-view
C-c C-r		diff-reverse-direction
C-c C-s		diff-split-hunk
C-c C-t		diff-test-hunk
C-c C-u		diff-context->unified
C-c C-w		diff-ignore-whitespace-hunk

C-M-i		diff-hunk-next
M-RET		diff-goto-source
M-SPC		scroll-up-command
M--		negative-argument
M-0 .. M-9	digit-argument
M-<		beginning-of-buffer
M->		end-of-buffer
M-?		describe-mode
M-K		diff-file-kill
M-N		diff-file-next
M-P		diff-file-prev
M-h		describe-mode
M-k		diff-hunk-kill
M-n		diff-hunk-next
M-o		diff-goto-source
M-p		diff-hunk-prev
M-{		diff-file-prev
M-}		diff-file-next
M-DEL		scroll-down-command
M-S-SPC		scroll-down-command
ESC <backtab>	diff-hunk-prev
ESC <mouse-2>	diff-goto-source
ESC <remap>	Prefix Command

C-x 4 A		diff-add-change-log-entries-other-window

ESC <remap> <undo>		diff-undo

* diff-hl use-package 

** descriptions
버전에서 변화된 것을 즉각 버퍼에 표시해서 변동사항을 실시간으로 확인한다
;; 추가필요한 것 파일저장전에 파일 저장내용을 비교하는 것이 어떤가
help:diff-buffer-with-file (diff-buffer-with-file) fesfsef
help:diff-backup 
** Codes
sdfasdfasdfasdf

Emacs is great - Ep 13 more faster git ussage
;; +! to signify file change on-the-fly https://youtu.be/UR2xZ4UY4h4
#+begin_src emacs-lisp :results silent
;; +! to signify file change on-the-fly https://youtu.be/UR2xZ4UY4h4

(use-package diff-hl
:ensure t
:config
(diff-hl-margin-mode)
)
#+end_src


#+begin_src sh :results silent
espeak -a 20 -v other/la "amare"
#+end_src


