


* 외부의 클립보드와 kill-ring의 관계설정값인 듯하다.
(setq save-interprogram-paste-before-kill t)
help:save-interprogram-paste-before-kill
I haven't noticed this problem before, but now I do. Found this:

(setq save-interprogram-paste-before-kill t)
I wonder why it's not the default.

oh man, this is exactly what I needed! 
I even started to write some defadvice for kill-ring-save when all I needed was sth to be t. 
Thanks!you



** emacs-xclip  0.9-1          0.03 MiB
;; 어떻게 연동할 것인가를 찾던 중에 임시로 발견함
;; yay xclip
Total Installed Size:  0.03 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                     [-----------------------] 100%
(1/1) checking package integrity                   [-----------------------] 100%
(1/1) loading package files                        [-----------------------] 100%
(1/1) checking for file conflicts                  [-----------------------] 100%
:: Processing package changes...
(1/1) installing emacs-xclip                       [-----------------------] 100%
==> To set up Emacs to automatically kill to clipboard and yank from clipboard,
    add the following to your ~/.emacs file (GNU Emacs) or ~/.xemacs/init.el
    file (XEmacs):

    (require 'xclip)
    (turn-on-xclip)
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

*** 해결의 방식 m-m f e d 를 실행해서 만들어 감.
(require 'xclip)
 ;; (turn-on-xclip) ;; 안되서 검색함.
 ;; To use, just add (xclip-mode 1) to your ~/.emacs or do `M-x clip-mode' ## 도움말 c-h P xclip로 발견함
 (xclip-mode 1) ;; 이것이 실행을 가능하게 함!
 
