#+STARTUP: showeverything indent
#+TITLE: 强點에 集中하여 眞我로 통합을 추구함 app/emacs/emacs_is_great.org
#+TITLE: 프로젝트.org
#+Core_VALUE: For WHAT?, WHY, and Meta
#+where_is_source_FILE: (find-file "~/config_github/app/emacs/emacs_is_great.org")
#+CREATOR: LEEJEONGPYO
###-*- coding: utf-8 -*-

* org-mode agenda 연구중
file:org_mode_study/agenda_view_org.org
agenda C-c [ 리스트에 추가하는 방식을 연구함.
       C-c / t ;;현재 폴더내의 TODO만 국한 
/app/emacs/org-clock-goto_C-u_C-c_C-x_C-j.org

* [concentration] 집중적인 노트의 통합이 가능하다
- 원칙발견실험중: 두기술이상이 합체할 경우 새로 파일을 만드는 것을 원칙으로 한다.
      - 사용기술:mpv, okular, python list ;; 이문장으로 쉽게 찾을 수 있게한다.
        - 파일위치제목: /app/emacs/원칙설명_이름정함.org

n과 w로 사용하는 법으로 集中의 노트를 사용하는 핵심의 기술이다!
(find-file-other-window "~/config_github/app/emacs/readme.org")
          强點에 集中하여 眞我로 통합을 추구함 app/emacs/readme.org
C-x n n         narrot-to-region
C-x n w         widen                 2019_12_diary.org
C-x n C-h       위의 설명을 보게함. 매우 중요한 특징으로 자주 활용할 것

** - 에서 [Alt키+좌우화살표]서열간격조정할 수 있음을 발견함. [Alt+Return]- 다음항목으로 넘어감 즉, 빠른 노트입력이 가능하다

** [탭자동파일명완성 발견 /*핵심어*]mini-buffer에서
* [Speed 빠르다] 링크를 자유롭게 사용할 수 있다.
** [org_id.org] 참조할 것 ~/config_github/app/emacs/org_id.org
- 파일명정확히 등록하면 우수한 색인파일을 생성하는 것을 가능하게 해서
** [footnote]내부색인기능 발견 C-c C-x f org-footnote-action    참고: 주석기능과 유사함. file:footnotes.org
emacs/test_stuff/like_pomodoro_timer_note.org

* [Expension 확장성] 다른 외부프로그램명령과 연동성이 높은 통합성으로 연결된다.

- mpv를 바로 실행함. /app/mpv/readme.org
    (find-file-other-window "../mpv/readme.org")


- espeak M-| 로 문서를 바로 읽어들이는 것이 우수함.
    (find-file-other-window "../espeak/readme.org:2")
  strings="$( cat )"; while true; do echo "$strings" | while read LINE ; do espeak -g 60 -s 100 -v other/grc "$LINE"; sleep 3; done; sleep 3 done
                ;; 단문으로 만드는 것은 시행착오를 거치면서 완성되는 것이다. espeak -g 60 -s 100 -v other/grc /la를 실행
                ;; C-x ESC ESC	repeat-complex-command
시행착오 완성된 영역선택에서 읽기를 실행하는 문장임( GREAT!!! )


- 브라우져로 YouTube시청 등의 기능 brave --incognito surf
    (async-shell-command "surf http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0167"
    (async-shell-command "surf http://www.google.com/ncr")
(eww  "http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0167")
(eww "http://www.google.com/ncr")
(eww "http://www.perseus.tufts.edu/")

(async-shell-command "brave --incognito 'http://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0167'")
(async-shell-command "brave --incognito 'https://www.youtube.com/watch?v=WBcvRW0CXfU&t=3m36s'")

    (async-shell-command "brave --incognito ''")
    (async-shell-command "brave --incognito ''")
    (async-shell-command "surf http://www.google.com/ncr")
    (async-shell-command "surf http://www.perseus.tufts.edu/")
* [미완성] vim과 비교하거나 다른 것을 연구해야 하는 것들
- ibus의 놀라운 한자입력완성기능이 있는데 ibus.el을 연구해볼것.

* TODO workflow/ 폴더를 만들어서 연구하고 연습을 하는 곳을 둘 것.
- 정확한 정의가 선명한 자신감과 불타는 의욕을 감응[etymology음원필요성]
'가가 가가?'
- 단어의 선정이 tool{선명함}이냐 workflow{포괄적}
- [사용에 기여하는 것] 
    - (대안제시) [정확한 단어주제]파일명검색(M-x find-grep 등)으로 찾아내는 것을 활용하는 메타관리규칙.
    # [find-name-dired *검색어*]일단 M-x locate로 파일명 검색보다는 M-x find-name-dired *검색어*
