
(원하는 도움말 기능을 바로 검색할 수 있을까?) 즉시 찾을 수 있도록 해서 유동성을 높인다.
# M-x{C-h f} *mark 탭으로 여러명령의 목록을 확인할 수 있다.
- [[info:emacs:Top]] 링커를 연결하는 것을 찾았음 더 정확히사용하려면 다른창으로 전달하는 것이 연구필요함.
[놀라움!] C-u C-x C-e (describe-function 'describe-function) [놀라움!- 한줄 아래서 실행히 붙임]
#("describe-function is an interactive autoloaded compiled Lisp function
in ‘help-fns.el’.



(apropos-command "region")
(describe-variable 'path-separator)
(describe-function 'bbg_mpv)
(describe-key (kbd "C-h m"))
                  (kbd "C-h m")
(describe-mode)
(help-for-help)

# (search-emacs-glossary) ;Emacs내부단어사전기능을 발견함! 정확하고 간결한 지식은 핵심열쇠다!


It is bound to C-h f, <f1> f, <help> f, <menu-bar> <help-menu>
<describe> <describe-function>.

(describe-function FUNCTION)

Display the full documentation of FUNCTION (a symbol).
When called from lisp, FUNCTION may also be a function object." 74 85 (button (t) category help-function-def-button help-args (describe-function "/usr/share/emacs/26.3/lisp/help-fns.el")) 204 212 (face help-argument-name) 249 257 (face help-argument-name) 293 301 (face help-argument-name))


# help:describe-package
(describe-package 'exwm)
(describe-package 'exwm-x)
(finder-commentary "org-pdftools")
(describe-package 'exwm)
(finder-commentary "pdf-tools")
(describe-package 'pdf-tools)


[놀라움!] C-u C-x C-e 변수명칭을 변경해서 사용할 것 (describe-function 'describe-function)
-



** help: [ (C-)M-/→자동완성 ]함수명생성과 file: 파일명생성의 방법에 사용 

- [ ]   M-/
	(dabbrev-expand ARG)
	Expand previous word "dynamically"
	to the most recent, preceding word for which this is a prefix.
- [ ] C-M-/
   ‘dabbrev-abbrev-char-regexp’
  start_1
  start_2
  start_3 asd calendar-cursor-to-date
  start_3
  start_4\\\ help: 만들기 쉬운 구조를 형성하기 좋다. 즉 C-h f를 누르고 함수 목록을 호출한 다음 필요한 부분을 당겨오면 가능하므로!

help: 만들기 쉬운 구조를 형성하기 좋다. 즉 C-h f를 누르고 함수 목록을 호출한 다음 필요한 부분을 당겨오면 가능하므로!

file: 구조도 쉽지 않을까 config_git/app/emacs/ src_1_line_execute.org src_tab_org_structure_completion_template.org
config_git/ 한 칸 띄워서 dired C-x C-f 로 불러낸 파일리스트나 목록에서 자동완성됨을 발견함
help.org info.org 등록할 것.

/home/thinkpad/config_github/hardware/


:(C-)M-/→자동완성:


#+begin_test org :목적=최고의 발성은 집중력강화의 비결이다!

- 강점: 
- 
 #+begin_center sh
# 문맥에 맞는 추론을 하는 것은 중요하다.

 #+end_center


- [ ] 구조파악할 것 ← 내부구조가 정확해야 활용을 높일수 있다
 #+begin_src sh :results table
  
  # 서열의 순서파악함. * > : > #+오그 > - [ ] > #+src
 #+end_src
  #+RESULTS:
  | #+RESULTS: 결과를 줄에 맞도록 띄울 것 hi2야호 |
 #+begin_src elisp :results table

   ;(indent-region START END &optional COLUMN)
 #+end_src
  #+RESULTS:
-      -> 구조파악할 것 > 범원리를 간략축적하고 > 이후연구,활용방향,추가필요 기록할 것





- 발굴의_과정들
 #+begin_src sh
   # 발굴되기 전에는 모든 것이 모르는 것이다!

   for i in 1 2
   do

       for i in 1 2
       do
           printf "hi"

           printf "hi"   
       done
   done
      echo history
   echo '#+RESULTS: 결과를 줄에 맞도록 띄울 것hi2야호'
   # [[ end   ]]

 #+end_src
  #+RESULTS:


- 문맥의 핵심부분을 다시 상기하는 과정을 최대한 단축하는 것이 오그모드의 최고 능력이다.
- 노트능력의 중요성- 문맥을 저장하는 기능이 필요함. 설득을 하려면 맥락이 중요하며, 중요한 맥락속에서 스토리를 전개하는 것이 필수적이다.


#+end_test



           :end:




** org_src_block_내부노트_모듈화_copy용_1형

:미주제1:


#+begin_test org :목적=최고의 발성은 집중력강화의 비결이다!

- 강점: 
- 
 #+begin_center sh
# 문맥에 맞는 추론을 하는 것은 중요하다.

 #+end_center


- [ ] 구조파악할 것 ← 내부구조가 정확해야 활용을 높일수 있다
 #+begin_src sh :results table
  
  # 서열의 순서파악함. * > : > #+오그 > - [ ] > #+src
 #+end_src
  #+RESULTS:
  | #+RESULTS: 결과를 줄에 맞도록 띄울 것 hi2야호 |
 #+begin_src elisp :results table

   ;(indent-region START END &optional COLUMN)
 #+end_src
  #+RESULTS:
-      -> 구조파악할 것 > 범원리를 간략축적하고 > 이후연구,활용방향,추가필요 기록할 것





- 발굴의_과정들
 #+begin_src sh
   # 발굴되기 전에는 모든 것이 모르는 것이다!

   for i in 1 2
   do

       for i in 1 2
       do
           printf "hi"

           printf "hi"   
       done
   done
      echo history
   echo '#+RESULTS: 결과를 줄에 맞도록 띄울 것hi2야호'
   # [[ end   ]]

 #+end_src
  #+RESULTS:


- 문맥의 핵심부분을 다시 상기하는 과정을 최대한 단축하는 것이 오그모드의 최고 능력이다.
- 노트능력의 중요성- 문맥을 저장하는 기능이 필요함. 설득을 하려면 맥락이 중요하며, 중요한 맥락속에서 스토리를 전개하는 것이 필수적이다.


#+end_test



           :end:






* 인접의 명령어 
method to make easy: macro help : link(쉽게 변환하여서 클릭으로 사용을 편리하게 만드는 법)
- 생산방법: [[file:kmacro.org::*macro%20help%20:%20link(%EC%89%BD%EA%B2%8C%20%EB%B3%80%ED%99%98%ED%95%98%EC%97%AC%EC%84%9C%20%ED%81%B4%EB%A6%AD%EC%9C%BC%EB%A1%9C%20%EC%82%AC%EC%9A%A9%EC%9D%84%20%ED%8E%B8%EB%A6%AC%ED%95%98%EA%B2%8C%20%EB%A7%8C%EB%93%9C%EB%8A%94%20%EB%B2%95)][macro help : link(쉽게 변환하여서 클릭으로 사용을 편리하게 만드는 법)]]

- Possible completions are:
help:describe-bindings
help:describe-buffer-case-table
help:describe-categories
help:describe-char
help:describe-character-set
help:describe-coding-system
help:describe-copying
help:describe-current-coding-system
help:describe-current-coding-system-briefly
help:describe-current-display-table
help:describe-distribution
help:describe-face
help:describe-font
help:describe-fontset
help:describe-function
help:describe-gnu-project
help:describe-input-method
help:describe-key
help:describe-key-briefly
help:describe-language-environment
help:describe-minor-mode
help:describe-minor-mode-from-indicator
help:describe-minor-mode-from-symbol
help:describe-mode
help:describe-no-warranty
help:describe-package
help:describe-prefix-bindings
help:describe-specified-language-support
help:describe-symbol
help:describe-syntax
help:describe-text-properties
help:describe-theme
help:describe-variable

* (describe-function 'describe-function)
It is bound to C-h f, <f1> f, <help> f, <menu-bar> <help-menu>
Display the full documentation of FUNCTION (a symbol).
When called from lisp, FUNCTION may also be a function object.


(elisp-index-search "elisp")

(Info-virtual-index)
(Info-index)

(Info-apropos-find-node "Help" "Help")
(Info-apropos-find-node FILENAME NODENAME &optional NO-GOING-BACK)

Apropos-specific implementation of ‘Info-find-node-2’.
Info-backward-node 	Info-copy-current-node-name 	Info-directory 	Info-exit
Info-final-node 	Info-follow-nearest-node 	Info-follow-reference 	Info-forward-node
Info-goto-emacs-command-node 	Info-goto-emacs-key-command-node 	Info-goto-node 	Info-help
Info-history 	Info-history-back 	Info-history-forward 	Info-index
Info-index-next 	Info-last 	Info-last-menu-item 	Info-last-preorder
Info-menu 	Info-mode 	Info-mode-menu 	Info-mouse-follow-link
Info-mouse-follow-nearest-node 	Info-mouse-scroll-down 	Info-mouse-scroll-up 	Info-next
Info-next-menu-item 	Info-next-preorder 	Info-next-reference 	Info-nth-menu-item
Info-on-current-buffer 	Info-prev 	Info-prev-reference 	Info-scroll-down
Info-scroll-up 	Info-search 	Info-search-backward 	Info-search-case-sensitively
Info-search-next 	Info-speedbar-browser 	Info-split 	Info-summary
Info-tagify 	Info-toc 	Info-top-node 	Info-undefined
Info-up 	Info-validate 	Info-virtual-index

* (Info-help) ;아래의 출력이 나오는 기본의 명령이다. 기초를 탄탄히 연구할 것.
(info "(info) Help")     기본기에 통달할 것!
 info:info#Help 
(Info-help)

  - Note Info mode shortcut by  ?Key Pressing on [2020-01-03 Fri 11:56] \\
    Info mode shortcut by  ?Key Pressing
    n move to the "next" node of this node.
    p Move to the "previous" node of this node.
    ^ Move "up" from this node.
    d Go to the Info directory node.
    < Go to the Top node of this file.
    > Go to the final node in this file.
    [ Go backward one node, considering all nodes as forming one sequence.
    ] Go forward one node, considering all nodes as forming one sequence.
    Tab Move cursor to next cross-reference or menu item.
    C-M-i Move cursor to previous cross-reference or menu item.
    f Follow a cross reference. Reads name of reference.
    l Move back in history to the last node you were at.
    r Move forward in history to the node you returned from after using l.
    L Go to mneu of visited nodes.
    T Go to table of contents of the current Info file.
    
    Moving within a node:
    SPC Normally, scroll forward a full screen.
    Once you scrool far enough in a node that its menu appears on the screen but after point, the next scroll moves into its first subnode.
    When after all menu items (or if there is no menu), move up to the parent node.
    DEL Normally, scroll backward. If the beginning of the buffer is already visible, try to go to the previous menu entry, or up if there is none.
    b Go to beginning of node.
    
    Advanced commands:
    s Search through this Info file for specified regexp, and select the node in which the next occurrence is found.
    S Search through this Info file for specified regexp case-sensitively.
    C-s, C-M-s Use Isearch to search through multiple Info nodes.
    i Search for a topic in thhis manual's Index and go to index entry.
     (comma) Move to the next match from a previous i command.
    I Look for a string and display the index node with results.
    M-x info-apropos Look for a string in the indices of all manuals.
    g Move to node specified by name.
     You may include a filename as well, as (FILENAME) NODENAME.
    1 .. 9 Pick first ... ninth item in node's menu.
    Every third '*' is highlighted to help pick the right number.
    c Put name of current Info node in the kill ring.
    M-n Select a new cloned Info buffer in another window.
    C-u C-h i Move to new Info file with completion.
    C-u N C-h i Select Info buffer with prefix number in the name *info*<N>.
    
    This mode runs the hook 'Info-mode-hook', as the final or penultimate step during initialization.


  - Note 기본키사용법노트 taken on [2020-01-03 Fri 11:53] \\
    n, p, u, tab, S-tab 기본키를 익힐 것.
  - Note taken on [2020-01-03 Fri 11:53] \\
    >> Type ‘n’ to move there.  Type just one character;
       do not type the quotes and do not type a <RET> afterward.
    
    ‘>>’ in the margin means it is really time to try a command.
    
    >> If you are in Emacs and have a mouse, and if you already practiced
       typing ‘n’ to get to the next node, click now with the left
       mouse button on the ‘Next’ link to do the same “the mouse way”.



(elisp-index-search "Key Help")

(elisp-index-search "Number")
(elisp-index-search TOPIC)
(Info-virtual-index "")
(Info-virtual-index "")


* 기본단축키
l(왼쪽에 있어서)	help-go-back
r(오른쪽 있어서)	help-go-forward

C-c C-b		help-go-back
C-c C-f		help-go-forward

TAB		forward-button
C-M-i		backward-button




‘<RET>’ echo hi
     Follow a cross reference at point (‘help-follow’).
‘<TAB>’
     Move point forward to the next hyperlink (‘forward-button’).
‘S-<TAB>’
     Move point back to the previous hyperlink (‘backward-button’).
‘mouse-1’
‘mouse-2’
     Follow a hyperlink that you click on.
‘C-c C-c’
     Show all documentation about the symbol at point
     (‘help-follow-symbol’).
‘C-c C-f’
‘r’
     Go forward to the next help topic (‘help-go-forward’).
‘C-c C-b’
‘l’
     Go back to the previous help topic (‘help-go-back’).


* 단축키모음

  - Note taken on [2020-01-03 Fri 10:50] \\
    C-c		Prefix Command
    TAB		forward-button
    RET		help-follow
    ESC		Prefix Command
    SPC		scroll-up-command
    -		negative-argument
    0 .. 9		digit-argument
    <		beginning-of-buffer
    >		end-of-buffer
    ?		describe-mode
    g		revert-buffer
    h		describe-mode
    l		help-go-back
    q		quit-window
    r		help-go-forward
    DEL		scroll-down-command
    S-SPC		scroll-down-command
    <XF86Back>	help-go-back
    <XF86Forward>	help-go-forward
    <backtab>	backward-button
    <mouse-2>	help-follow-mouse
    <remap>		Prefix Command
    
    C-c C-b		help-go-back
    C-c C-c		help-follow-symbol
    C-c C-f		help-go-forward
    
    C-M-i		backward-button



* 




