#+STARTUP: showeverything indent

 - [[원음의 속성을 파악]]

* [본질 인식]은 단어이해는 문법과 분리될 수 없다.
* {linage} * super -> ** side -> *** stuff
* [1_super_1]: 通合性 meta_method workflow emacs/readme.org::{linage}
- /great_books/meta_thought.org
** [2_side_2]: idea_practice: ./test_reading_stuff.org ./test_stuff/
       - sible, /vim/readme.org
*** [3_stuff_3]: simple_practice, dividen_note_making, etc. question? test develop
        - ./test_stuff/
#+BEGIN_SRC emacs-lisp
(find-file-other-window "./test_stuff/readme.org")
#+END_SRC
** test_list.org 리스트로 목록을 수립하고, ./test_stuff/각각의.org
* 원음의 속성을 파악하는 것etymology에 관하여 readme.org 그리스어 라틴어 greek latin
  - [ ] y음은 이를 꽉물고 약하게 '으~'위 소리를 내고(이와 유사하게 약음으로발음) oy는 우로 낸다
  f v   이를 꽉물고
  ks, th, ps   이를 꽉물고 ㅋ(스-으) ㅌ(스-으) p(스-으)
  kh, th, ph(f)   이를 꽉물고 ㅋ(
  ,a ,h ,o   이를 꽉물고 '흐~'(아) '흐~'(ㅐ(ㅔ)ㅣ) '흐~'(오)
  - [ ] amare es er로 변환되는 것
     '스' 가 '르r' 로 변환되는 것
  - 갇, 갓 같 갔
     '드' 가 스 쓰 트 를 대표하는 것
  → 즉, 스 드 쓰 트는 동일한 음원의 뜻을 지닌다.

  - 음원의 아이디어를 모은다!
그리고 매우 주관적이면서 노력이 가미된 개성화된 구조를 발견한다.
* 주변의 단어를 모두 적어서 원하는 방식으로 표현하는 것을 개선한다.
- [손동작을 넣는다] 손가락으로 가르키면서 직접가르키는 연습을 한다. 명확한 동작을 넣는다.
아침에 일어나면 원하는 단어를 적어서 사용하는 것을 연구하기 쉽게 만든다.
- [근사록] 주변의 가까운것을 찾는다 옷을 갈아입다
단추, 단추를 잠그다 
- [말하는 것을 연습한다] 아침부터 연습을 한다.
- 출처: [[https://www.youtube.com/watch?v=rLlLVtLtE3I][My SECRET For Learning Multiple Languages - TRY IT! - YouTube]] 

로마는 하루아침에 모방이 아니다 그것은 끊임없는 지속적인 개선의 노력이며, 성실함이다.
사고의 단련과 구현을 위한 노력이 필요하다.
17:30 experiment at best. The Roman military
system was successful as a package deal
all of its elements worked together such
that its whole was greater than the sum
of its parts.
Therefore just copying bits and pieces
wouldn't get you the same results. Yeah
Your imitation legions might look and
even feel like the real thing on the
training field, but it won't hold up in
the rigors of war. [[https://www.youtube.com/watch?v=dfKNbuxekEo][Why Didn't Anyone Copy the Roman Army? - The Imitation Legions DOCUMENTARY - YouTube]]
