


** 자막을 다운로드함
youtube-dl --write-auto-sub --convert-subs=srt --skip-download URL


/home/thinkpad/config_github/language_computer/haskell/monad.org
 https://www.youtube.com/watch?v=fCoQb-zqYDI
youtube-dl --write-auto-sub --convert-subs=srt --skip-download  https://www.youtube.com/watch?v=fCoQb-zqYDI
youtube-dl --sub-lang en --write-auto-sub --convert-subs=srt --skip-download  https://www.youtube.com/watch?v=fCoQb-zqYDI
youtube-dl --sub-lang en --write-auto-sub --convert-subs=srt --skip-download https://www.youtube.com/watch?v=CT0HvjWoIqE
youtube-dl  https://www.youtube.com/watch?v=CT0HvjWoIqE
https://www.youtube.com/watch?v=02_H3LjqMr8&t=1169s
 위의 2명령중에서 사용할 것!
--sub-lang en 
좋은 출처 : [[https://superuser.com/questions/927523/how-to-download-only-subtitles-of-videos-using-youtube-dl][How to download only subtitles of videos using youtube-dl - Super User]]

** yay google2srt 다운로드실패함

** /usr/bin/vtt2srt - yay vtt
;; 그냥 vtt로 사용하는 것이 간편할 지도 모른다. 변형시 출력의 수정이 필요할 지모른다.
2 aur/vtt2srt-git r12.e0c6a9c-3 (+0 0.00%) 
    Lightweight WebVTT (VTT) to SubRip Text (SRT) subtitle converter.
1 aur/vttest 20140305-2 (+7 0.00%) (Orphaned) (Out-of-date 2019-01-23) 
    tool for testing VT100 compatibility of terminals
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 2
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make: 1]  go-2:1.14.1-1
[Aur: 1]  vtt2srt-git-r12.e0c6a9c-3
 which vtt2srt 
/usr/bin/vtt2srt


$ vtt2srt 'What is IO monad-fCoQb-zqYDI.en.vtt'
Done.
$ vtt2srt 'How Monoids are useful in Programming-BovTQeDK7XI.en.vtt'
Done.

** test
