#+TITLE: 원반 최고자아원형원리관통! 어원혁명, 멘탈중력장
#+CREATOR: LEEJEONGPYO
#+STARTUP: showeverything indent latexpreview


File-Reminder를 만들어 강력히 활용함!
(find-file-other-frame "~/config_github/great_books/mental_reminder.org")

*둥근 원반의 관통!* 관통관통! 철저관통! 진리가 보고 싶다. "화두70현상30"
아는 힘(자아의 본질)을 강력히 간다(삼매)=즈나나 요가
자신을 알라!(핵심과제-라자비젼.최고학문.자아탐구, 심리적 원형질서) 자신의 시간을 알라!
- 단점을 잘 파악하고 유리한 전략을 수립할 것.
- 자아를 가짐보다 높음이 없다! 자기가 진정 무엇이며, 무엇을 원하는지를 물어보지 않는다.
  자기를 잘 applicate하라! 먼저 자신을 알아라.(실현에 앞서서)
- 늘 이것! 가장 깊은 이 무엇인가! 무엇이 궁극의 실체인가! 늘 경외하며 살핀다. 지혜를 추구 탐구한다
	- 늘 하고 있는 것이 마음에 담긴 것이며 곧 그 사람의 인격이며 인생이다
- 자기를 사랑하라(남이나 밖보다 우선하여서, 내부질서가 더 중요하다)
공부는 내부질서의 회복이다.
마음의 지분의 퍼센트가 어느정도인가? *초자아의 강력진동파동으로 상황돌파*
가장 신적이면서 가장 높은 힘의 권능으로 그것을 친다! 회광반조! 금강반야바라밀(앎의 다이아로 앎의 원인을 친다)

[2020-01-01 Wed] 自由 ! 깊게 갈아서 자득自得이 중요함!(자기自己에게 가장 최적화된 방식으로 터득得하는 것)
(최대한 깊고 강력하게 Binding됨을 추구함+느리더라도 결국에 효과적인 개성화 자화된 자아의 것)
- 자제의 힘으로 목표를 정하고 내부의 강력한 세계를 구축함. 외부와 강한 공명감동함. 연동형.
- 맹목적인 외부에서 주어진 허구에 대한 저항권으로 자신의 가능성을 표출함
;; 반복적 과정을 매우 효과적으로 강화하는 리엔지니어링의 과정이다. steve_jobs
(async-shell-command "mpv ~/Music/St* --ab-loop-a=1:58 --ab-loop-b=2:08 --start=1:53 --volume=39")




- 늘 하고 있는 것이 마음에 담긴 것이 곧 그 사람의 인격이며 인생이다 늘 지분을 모아서 돋보기처럼 모은다.
- 진리(소자아)로 진리(대하느님,대진여)를 파고든다! 자주 생각하는 것이 사랑하는 것이다! 최우선의 가치
- 초정밀이성으로 본래자신을 이성한다. 자기반추며, 자기희생, 호흡희생, 철저희생, 목숨희생, 시간희생, 최고지식의 희생
** self-applied function 자기반추적인 기능(우주의 운행작동-로고스의 직접구현됨) [2019-11-11 Mon 16:47] 
- 구현되는 사물에 로고스는 결정력을 지니는 것으로 생각된다. {lazer의 신호강화원리- 야곱의 사랑받는 원리}
- 대학(로고스의 초자아)은 무지의 최전방이다. 진리의 방패(원리지배력)가 영토 유지하고 그 창(화두참구)이 확장시킨다.
  자기를 자기에게 최우선(자애)작동시킨다.(진정한 혁명=창조적 혁명을 자발적으로 자력으로 탐구혁신(요가=Yoke=자율)한다!)
something called self application - it's the idea of applying something to itself.
원형을 깊고 생생히 파악하고, 정확히 이해하며, 명확하고 간결하게 구현한다.

- 한계를 돌파한다. [2020-01-11 Sat 12:00] 최고 원리에 도달 자아의 가장 높은 곳을 향하여!
  목표를 생생히 추상하며, 되뇌이며 반복의 프로세스를 거듭하며 침착하게 인내하며 버틴다.
  헤라클레스의 무명여인과 악덕여인의 유혹- 참된 행복은 노고와 단련으로 성립한다.
  일체 모든 것이 참된 것에 뜻을 두면 광명에 의해 그 효력을 상실한다.
	갈리면서 진행된다는 것을 믿으며,,, 욕망극복의 호기심, 조금씩 갈아들어간다.
	안되면 더욱 1000배나 더 힘을 가한다.(돋보기의 포커스를 맞춘다)
	화두가 성성적적함 무색무미해도 결국에 단맛을 낸다!(진미담미)
	또는 강력히 옳바른 길을 선택하고 *초자아의 강력진동파동으로 상황돌파* 최적의 방법을 찾는다. 곤의 강력!
	더욱 중요한 것은 높은 이상(초자아의 추구)이 있을 경우에 욕망의 한계를 뛰어넘는다.
	끊임없는 닦음과 집착없음으로 자아를 가져라! 이 몸에 오고가는 것은 덧이 없다.
	선별의 선발장(중력이 지배하는 데 더 상위원리가 어찌 방관만 하겠는가)
	에너지 장벽을 관통할 의지와 탐구적 열정이 있는가?!

*초자아의 강력진동파동으로 상황돌파*
불타는 눈을 가지고 
어떠한 고난과 역경 속에서도 자아의 확장질서과 앎의 궁극적인 통찰가치,
냉철한 이성과 결심으로 꾸준히 지탱하며,
냉철한 이성으로 본질을 관통하여 끝까지 지탱하는 역량으로 
화산이 폭발하는 의지로 최고지식의 희생목숨을 던질 각오로 돌파한다.

무색무미함... 담담맹맹함. 성성적적한 화두의 힘!
처음에 소태와 같이 쓰나 결국에 가장 단맛이 난다.(인내는 쓰지만 그 열매는 달다)

<무서운 힘으로> 궁극의 실체적 가치(왜인지?)를 주야로 묵상한다. 회광반조!
수학의 미학의 <다이아몬드>가 불멸이라! 강력한 힘을 추상으로 끓어오르게 직공 타격한다.
회광반조! 금강<다이아몬드>반야바라밀(앎의 다이아로 앎의 원인을 친다! 하심!)
아테나의 창과 방패로, 무지의 산을 박살낸다!
혼돈의 대적을 천개의 눈과 무기로 즉시 박살 항복시킨다. 지장살격!!!
무지의 무리를 기와장부수듯이 박살낸다.

지축을 부러뜨릴 기세로, 하늘을 찌를 기상으로! 우주를 폭발시키는 파괴의 힘으로 무지를 박살낸다.
산토를 파괴할 힘으로 만산만겁의 존재의 힘으로 극강의 힘으로!

* 강력한 언어의 이미지력을 강화한다! 어원을 파고든다.(어원혁명!) 그리스어의 그림원형을 다운로드함(어원의 어원이므로 매우 중요함)
( *어원을 철자 그림으로 추단한다 漢字처럼 내부질서의 창조행위=자유의지* )
- 보다 세부적으로 철자철자 마다마다 낱낱이 섬세한 감각을 파고든다.
- 내부의 언어세계를 완전히 장악하고 통치하는 왕국을 성립한다.
- 야곱의 하느님과 같이 창의력 상대에 맞게 최대한의 개성화로써 구현한다.
- 늙은 짐승과 권위적인 허수아비 야수를 제압하여 법칙에 맞게 다스릴 권능이 인간에게 있다. [2020-01-10 Fri]  
(find-file-other-frame "~/config_github/great_books/mental_reminder.org")
열등감을 도전의 힘으로 전환한다. 시간적 의미를 변경함 - 우주를 재창조 - 공명진동- 안암학사의 별관의 로비의 비누냄새 학습의 동기를 폭발적으로 증대한다.  [2020-01-09 Thu 19:41] 

그리스 알파벳- 글자마다 인식을 그림으로 구체화시켜서 명확히 한다. [2020-01-09 Thu 16:30] 
- (창조력발동!)어원의 이해를 더욱 더 파고들어 어원의 연원을 추단한다. [2020-01-09 Thu 19:36]
  인식의 발달이 자신의 성격을 구현하는 것이다.
- 자판의 손가락도 같이 만들어서 이해를 굳힌다.
- (해석) 무의식적으로 깊은 연관성이 형성되므로 무시할 수 있는 사안이 아니다.
	혁명적인 학습이다. 예감적 [2020-01-09 Thu 19:41] 공명진동 안암학사의 별관의 로비의 비누냄새가 학습의 동기를 폭발적으로 증대한다. ( *어원을 철자 그림으로 추단한다 漢字처럼 내부질서의 창조행위=자유의지* )

* basis 강화= 오직 최고의 기반이 되는 것, 반복의 달인!- 꾸준히 지분을 늘리고 기여를 하라!
- 잡스 오직 기본을 다지는 것이 가능할 뿐이었다.
- 특히: 어원인식력, emacs, 정확한 손가락의 감각리듬.
- 높은 호환성(Integrety)을 유지하는 비결이 된다. 기본(Basis)에서 개성분화발달을 추구하는 것이 합리적이다.


- 자아로 자아를 연마한다.[2020-01-11 Sat 12:30] 오직 1번을 잡으라!
* 오직 본질의 핵심의문을 중요시 하라!(희랍인의 본질추구의 성향=>행복)
** 최대한 간결한 핵심을 잡아라!(산만한 복잡한 설정에서 개성화로 승부)
* [개발 자료] 맨탈 중력장의 힘 (무궁무진한 에너지의 근원에 접근할 가능성...)  초자아의 강진동 파동형성
- 아리스토텔레스(황금의 강)의 경구를 따로 읽어 들일 것. 잡스의 북유럽 아리스토텔레스 멘토.
- 에너지(희생정도), 진동(음의 진동_진퇴_진화, 반복의 탬포, 타격감의 생동감의 리듬), variance(편차-산란분포)
  희생의 결의강도(중량),  생각의 횟수(자주),   생생하고 정밀한 집중타격(몰입.삼매). - 무조건 목표를 3발 쏜다.

- 늘 하고 있는 것이 마음에 담긴 것이 곧 그 사람의 인격이며 인생이다

- 경제는 value시간이며 통찰해결책놀라움이라는 동영상! 
	앎의 확장이 인간영역의 확장으로 이어짐! 경제는 앎의 수준을 반영함.
- 자신의 발달(개인자아의 확장) 조직의 발달(사회자아의 발달) 사회의 발달(초자아의 발달)
- 자유의 발달(앎의 가치-지력)  정의의 구현(황금률-신뢰)    진리의 확장(간결한 원리의 통치권, 깨달음, 구원)
- 열성(동성=자발Yoke 통제반조) 암성(무기물=관대함과 연민)  지성(선성_빛=무(한자)아)
- 무의식을 바꿀 수 있는 혁명력!
인생관, 사회관, 우주관(신학,철학,불교,종교,화엄)
명명덕, 친민,   지어지선 대학의 3강령



- 화두화엄 화두70현상30
(심층)무의식에 넣지 않으면(삼매) 자기(의미) 공부(진정한 재산사랑) 아니다!

염불(지금 마음은 사람이 아니다!)

- 소크라테스=무지의 지가 오히려 진지함
  - 도가의 무위=철저히 모를 뿐!


- 수레의 비유
  - 소아의 마부(에고)가 주인(크리)의 뜻을 살펴 말(감각과 욕망)을 다스려(고삐-이성) 집(하늘나라)에 이르는 것이 인생의 목적!
    - 가장 높은 지식의 희생을 치르는 것.
- 가장 사랑하는 사람이며 가장 소중한 사람이다.(야곱의 경우)
    - 진리를 사랑하는 사람에게 어찌 궃은 일이 있으랴 즉시 모든 허물과 죄가 사라진다!!!
      너는 하늘에 속한 자이므로 일체 두려움을 던져두고 참됨에 (진지함)몰입하라!
      자아로 자아를 높일 지니!!!


- 목숨을 걸만큼 가치가 없다면 그것은 숫가락 가치가 없다. 늘 있으면서 항상하는 가치를 추구한다.
-진성바탈에 이르기 위하여 1번으로 전력을 다해 돌진하는 용사보다 아름다운 자는 없다.
-진리가 보고싶다. 이르고 싶다(자유의지-진리구현자).-바른생각은 정각을 이룬다. 대천세계칠보보다 가치있다.

자신을 알라!(핵심과제-라자비젼.최고학문.자아탐구) 자신의 시간을 알라!
- 단점을 잘 파악하고 유리한 전략을 수립할 것.
	- 어느정도 역량욕구를 가지고 무엇에 잘 하는 지. 단점으로 흐르는 것을 차단하는 법
	- 슬럼프 극복의 방식연구: - 악인을 허용하는 법계성에서 높은 관용도와 도전을 감화받음!
	  진정한 믿음은 드물다 정신희유-금강경의 품명

- 사회의 계급통치는 사실상 역사적인 현상.
즉, 속임수를 사용한 것이 대부분, 노예적 무지와 우상적 기생계급에 근거함. 홈스쿨링의 필요성!
- 그러나 단련의 세상은 탈곡기와 같아서 실제를 창조력의 구현의 합당한 선별장!
진정성과 가치없이 전시적인 허세부리다가 허망붕괴한다.(남이나 밖보다 우선하여서, 내부질서가 더 중요하다) 건축추구하다가 빈_깡통지킨_개꼴
- AI는 높은 초자아적인 질서를 요구한다! 속도는 부차적이며 공허한 파멸인가 영원의 자유인가의 갈림길이다.
	창조의 원리가 있는가?

자유시간과 여가를 낭비하면 노예가 되는 문책이 따른다.

- 미국의 적은 무지와 무능과 미신이다.
- 무엇을 기여할 수 있을까?(Integrety 진정성있는 자세는 중력보다 상위의 법칙존재를 속일 수 없다)
	- 무한을 가장 사랑하는 자, 가장 버티는 자, 최우선인 자!

- Outwitting Devil
  자신이 무엇인지 가치있는 탐구와 물음을 제기하는 태도가 중요함.
마음에 담은 것(사랑하는 탐구지력)이 소리(언어)처럼 라디오(물질파)처럼 물질계에 공명진동함.


- 자아는 인간의 목적지 융의 심리학
자아발견과 과정에서 많은 창조적인 아이디어가 발굴된다. 언어적인 음가는 창의성으로 재발굴되면서 
무의식을 끌어올려 발굴한 상징체계를 개발하는 것이 훌륭한 사회다. 심리적 모순을 해결하는 것이다. 여가의 시간을 활용한 심적탐구의 성과가 문명임!
아이디어!-심리적, 물리적으로 공통된 원리에서 도출되는 것이다.(천인합일)
컴플렉스는 최고의 에너지원(희생의 결심)이다! 열등감은 더 나은 혁신의 동기이며 에너지원이므로 소중히 통찰하고 잘 습득할 필요가 있다.

- 물리학 물질파
진동의 널뛰기처럼 힘의 증폭이 이루어짐다. 에너지(무게) 파장(뛰는 빈도) 편차(집중도_지력의 돋보기오차를 줄임)
지구의 가장 강력한 지진은 축적을 이루어서 성립되는 파장에너지다.
물질파는 진동으로 영향력을 행사하는 것으로 볼 수 있지 않을까!?
거시진동과 별도로 여러 층의 미시진동리듬이 존재한다.
심리현상도 음의 진동에 감응한다. 따라서 에너지는 진동이다.
음성에서 모음은 넓은 파장대를 구사하고 자음은 그것의 분산을 조절한다.



- 이정표(반복의 달인) 화두가 성성적적한가!
	- Arco linux 반복폴더 test_키워드 작동시킬 것
	(find-file-other-window "~/test_config_github/great_books/mental_reminder.org")




buffer-find-file

; Run by C-u C-x C-e
buffer-file-number
(3282990 2049)
#+BEGIN_SRC sh :results raw
(ls -i "/home/thinkpad/config_github/great_books/mental_reminder.org")

#+END_SRC

#+RESULTS:
3282990 /home/thinkpad/config_github/great_books/mental_reminder.org


buffer-file-number

(car buffer-file-number)
3282990

(async-shell-command "okular \"$(find ~/Music  -inum 6836311)\" &")
(3282990 2049)
