
하스켈을 익히기 위해서 설치를 시도함.
[2020-01-14 Tue] 맥북을 내부청소하고 쿨링 작업을 위해 먼지청소와 써멀을 발라줌.
[2020-01-15 Wed 09:37] sudo pacman -Syu xmobar
touch ~/.xmobarrc

refresh "xmonad --recompile && xmoad --restart

quit xmonad is 
mod is opt 

opt + shift + return terminal
mod-p launch dmenu
mod-space rotate throught the available layout algorithms
mod-shift-space Reset the layouts on the current workspace to default
mod-n Resize viewed windowns to the correct size
mod-tab Move focus to the next window
mod-j Move tocus to the next window
mod-k Move focus to the previous window
mod-shift-c Close window
mod-drag


~/.xmonad/xmonad.hs
locate xmonad.sh
/usr/share/xmonad/man/xmonad.hs
cp /usr/share/xmonad/man/xmonad.hs ~/.xmonad/xmonad.hs

mod1 IS ALT KEY
mod4 IS SUPER KEY
RESTART is Mod+q

yay xmonad-contrib # 설치를 권고받음. https://youtu.be/JLz3UKJFMoI?t=1250

.config/xmobar/.xmobarrc 폴더를 만들어야 실행된다고 함.

** 강점 (dwm과 비교하여서)
- 레이아웃을 각각 다르게 미리 지정할 수 있다.
      !!또한 배열과 순서를 전혀 다르게 짤 수 있다!!!
- 변경을 직접바로 즉시 실행할 수 있다.
- 하스켈을 공부할 수 있다!

# .config/xmonad/ 폴더에 저장할 수 도 있다하니 고려할 것. xmonad.hs




