

(man "vim")   /home/thinkpad/
(man "urxvt")        urxvt [options] [-e command [ args ]]
;; :help ë¥¼ ì‹¤í–‰í•˜ëŠ” ê²ƒìœ¼ë¡œ ë¬¸ì„œì— ëŒ€í•œ íƒìƒ‰ì„ ì‹œë„í•œë‹¤.
* ì²´ê³„ì ì¸ í•™ìŠµê³¼ ì—°êµ¬ë¥¼ ìœ„í•œ ëª…ë ¹ì „ì†¡ê³¼ helpë¥¼ ì´ìš©í•  ë°©ë²•ì„ ë°œê²¬í•˜ë ¤ê³  í•¨.
- í„°ë¯¸ë„ì˜ ì™¸ë¶€ë¥¼ ë¹ ë¥´ê²Œ ì‹¤í–‰í•˜ëŠ” ë²•ì„ ì°¾ì•„ëƒ„.
(start-process "vim_in_urxvt" nil "urxvt" ;; ë¹ ë¥¸ ë‹¨ì¶•ìœ¼ë¡œ ë§Œë“œëŠ” ê²ƒì€ C-c C-l elisp: ë¥¼ ì‚¬ìš©í•´ì„œ ë„£ìœ¼ë©´ ë¨
  "-e" "vim")   ;ì„±ê³µì ìœ¼ë¡œ ê°€ëŠ¥í•¨ì„ ë°œê²¬í•¨.
(send-string "Shell" "k")
(process-send-string "*Async Shell Command*" "iworld")



help:async-shell-command

(async-shell-command "espeak -a 30 hi" "abc")

(async-shell-command "urxvt" nil nil)

- ìš°ì„ ì ìœ¼ë¡œ ë¬¸ì¥ì„ ì „ì†¡í•˜ëŠ” ë²•ì„ ìµí˜

process-send-eof
process-send-region
process-send-string    help:process-send-string
(process-send-string "vim in urxvt" "iworld")
(process-send-string "vim_in_urxvt" "iworld")
(process-send-string 3687846 "iworld")
help:process-send-eof (process-send-eof "vim_in_urxvt")
help:process-send-region (process-send-region "vim_in_urxvt" 1 100)
process-send-string

help:python-shell-send-region
help:send-region (send-region "vim_in_urxvt" 1 100)
help:sh-send-line-or-region-and-step

- *terminal* ë¡œ ì „ì†¡í•˜ëŠ” ë²•
help:term-send-region (term-send-region "vim_in_urxvt" 1 100)
help:term-send-region (term-send-region "*terminal*" 1 100)
help:term-send-string (term-send-string "*terminal*" "ë¬¸ì¥ì „ì†¡ì´ ì„±ê³µì ì´ë‹¤.")
help:term-send-string (term-send-string "*terminal*" "vim -h move")
help:term-send-string (term-send-string "*terminal*" ":help move")

- *shell* ë¡œ ì „ì†¡í•˜ëŠ” ë²•
    M-x shell
M-: (sh-send-line-or-region-and-step) ;; ì•„ë˜ë¥¼ ì„±ê³µì ìœ¼ë¡œ ì˜ì—­ìœ¼ë¡œ ì‹¤í–‰í•¨
echo hi
echo world
echo echo hi
echo echo world
espeak -a 30 hi

espeak -a 30 hi

espeak -a 30 world
:!q


- *eshell* ë¡œ ì „ì†¡í•˜ëŠ” ë²•
help:send-string (send-string "abc" "abc") (send-string "*eshell*" "k")
 - ë‹¨ ì‹¤í–‰ì¤‘ì¸ í”„ë¡œì„¸ìŠ¤ê°€ ìˆì–´ì•¼ í–ˆìŒ.ìœ„ì˜ ê²½ìš°ëŠ” mpvë¡œ ìŒì•…ì¬ìƒì„ í†µì œí•˜ëŠ” ê²ƒì´ ê°€ëŠ¥í•¨.

python-shell-send-region
send-region
sh-send-line-or-region-and-step
term-send-region

(list-processes)




- ë‹¤ë¥¸ë°©ë²• M-x term vimì„ ì‹¤í–‰í•˜ëŠ” ê²ƒì´ ìˆìœ¼ë‚˜ ë©€í‹°í„°ë¯¸ë„ì„ ì‚¬ìš©í•´ì•¼ í•  ê°€ëŠ¥ì„±ì´ í¬ë‹¤.

(start-process "emacs_pdf okular" nil "okular" ;; ë¹ ë¥¸ ë‹¨ì¶•ìœ¼ë¡œ ë§Œë“œëŠ” ê²ƒì€ C-c C-l elisp: ë¥¼ ì‚¬ìš©í•´ì„œ ë„£ìœ¼ë©´ ë¨
  "-p" (int-to-string (+ 57 24)) ;-p 57; query_string.org
  "/home/thinkpad/Documents/learning_gnu_emacs.pdf" )


       --help      Give a help message and exit, just like "-h".
       -h          Give a bit of help about the command  line  arguments  and
                   options.  After this Vim exits.
       /etc/vimrc     System wide Vim initializations.

       ~/.vimrc       Your personal Vim initializations.

       /etc/gvimrc    System wide gvim initializations.

       ~/.gvimrc      Your personal gvim initializations.



info:screen#Top
file:../vim/index.org
file:../tmux/index.org


       /etc/vimrc     System wide Vim initializations.

       ~/.vimrc       Your personal Vim initializations.

       /etc/gvimrc    System wide gvim initializations.

       ~/.gvimrc      Your personal gvim initializations.
