#+TITLE: xrander_collection_caffeine.org
#+CREATOR: LEEJEONGPYO
#+STARTUP: showeverything
xrandr -q # 기초자료출력함!

$ xrandr --output eDP1 --brightness 0.5 #화면밝기조정하는 명령
[thinkpad@msata045 ~]$ xrandr --output eDP-1 --brightness 1
[thinkpad@msata045 ~]$ xrandr --output eDP-1 --brightness .1
[thinkpad@msata045 ~]$ xrandr --output eDP-1 --brightness 1

xbacklight -get
xrandr --verbose

$ man 1 xrandr reveals a --set <property> <value> option.
$ xrandr --output <output> --set BACKLIGHT <value>

I use this to increase/decrease my backlight in about 1/40 steps:

$ xrandr --output eDP1 --set BACKLIGHT $(( $(xrandr --prop | awk '/^eDP1/,/^DP1/{if ($1 ~ /BACKLIGHT/) {print $NF; exit} }') + (852/40) ))
$ xrandr --output eDP1 --set BACKLIGHT $(( $(xrandr --prop | awk '/^eDP1/,/^DP1/{if ($1 ~ /BACKLIGHT/) {print $NF; exit} }') - (852/40) ))
[ -w /sys/class/backlight/intel_backlight/brightness ] || gksudo chmod 777 /sys/class/backlight/intel_backlight/brightness
echo 50 > /sys/class/backlight/intel_backlight/brightness
sudo su ; echo 4794 > /sys/class/backlight/intel_backlight/brightness
xrandr --output eDP-1 --brightness 976
xrandr --output eDP-1 --brightness 1



$ xrandr --output eDP-1 --rotate {left, right, normal, inverted}
eDP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 344mm x 193mm
eDP-1 connected primary 1080x1920+0+0 right (normal left inverted right x axis y axis) 344mm x 193mm
eDP-1 connected primary 1080x1920+0+0 left (normal left inverted right x axis y axis) 344mm x 193mm
eDP-1 connected primary 1920x1080+0+0 inverted (normal left inverted right x axis y axis) 344mm x 193mm

$ xrandr -o normal # 이명령도 간단하지만 잘 실행 된다.
$ xrandr -o left


xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 # 수정해서 사용할 것.

 xinput set-prop "my device" "my prop" 1 2 3
 xinput set-prop "my device" "my prop" 1 2 3

###xinput list-props
xinput --list [--short || --long || --name-only || --id-only] [device]
xinput --list-props device [device [...]]
$ xinput --list-props "Virtual core pointer" # 매우 잘 나온 값의 참조가 된다.
Device 'Virtual core pointer':
	Device Enabled (163):	1
	Coordinate Transformation Matrix (165):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000

$ xinput --list-props "TPPS/2 IBM TrackPoint"
Device 'TPPS/2 IBM TrackPoint':
	Device Enabled (163):	1
...	Coordinate Transformation Matrix (165):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
# 위의 값이 float이므로 
xinput set-prop 'ELAN0732:00 04F3:2536 Pen (0)' --type=float "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1


성공한 left rotation both mouse screen 
#+BEGIN_SRC sh
	# 트랙포인터만 돌리는 것으로 실험함. id=17
	## 화면돌리기 부터실험함.
	xrandr -o left
	## 마우스 트랙포인터만 돌리기
	xinput set-prop 'TPPS/2 IBM TrackPoint' --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
	xinput map-to-output 17 eDP-1 # 17 is TPPS/2 IBM TrackPoint
#	xinput set-prop 'USB Optical Mouse' --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
#	xinput map-to-output 12 eDP-1 # 12 is USB Optical Mouse

#+END_SRC

#+RESULTS:



#+BEGIN_SRC sh
	# 트랙포인터만 돌리는 것으로 실험함. id=17
	## 화면돌리기 부터실험함.
	xrandr -o normal
	## 마우스 트랙포인터만 돌리기
	xinput set-prop 'TPPS/2 IBM TrackPoint' --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
	xinput map-to-output 17 eDP-1 # 17 is TPPS/2 IBM TrackPoint
	xinput set-prop 'USB Optical Mouse' --type=float "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
	xinput map-to-output 12 eDP-1 # 12 is USB Optical Mouse

#+END_SRC




I tried: unexpected type for property 'Device Node' But I got the error:
by $ xinput set-prop 16 "Device Node" /dev/input/event15



# cf. xbindkeys for shortcut setting XF86HomePage

영감님을 만나고 악을 다시 선으로 변환하는 능력의 발굴!
[2019-11-14 Thu 20:35] * xrandr * (find-file "~/config_github/app/xrandr/readme.org")
*** xrandr * (find-file "~/config_github/app/xrandr/readme.org")
*** 사용의 목적: 효과적인 다중모니터구성의 원리발굴.
*** (find-file "~/config_github/app/xrandr/readme.org")
* xrandr --auto --output eDP-1 --auto --right-of VGA-1 # 잘 작동됨!

what kind of actions they are
concerned with, (2) what sort of mean justice
is, and (3) between what extremes the just act
is
 intermediate.

* # 모니터가 단일화 복귀 ;;; (async-shell-command "xrandr --auto --output eDP1 &")
* # 왼쪽에 외부모니터가 옴 ;;; (async-shell-command "xrandr --auto --output eDP1 --auto --right-of VGA1 &")
* # 노트북잭왼쪽 오른쪽외부모니터 ; (async-shell-command "xrandr --auto --output eDP1 --auto --left-of VGA1 &")
* # xrandr --output LVDS1 --auto # to get back to the default mode
* # xrandr --output VGA1 --off # you may also disable on e optput using.https://xorg-team.pages.debian.net/xorg/howto/use-xrandr.html
