#!/bin/sh
# locate xinitrc # 이 파일을 find하는 방법은 locate CMD
## like file saved in /usr/local/etc/X11/xinit/xinitrc in FreeBSD
## this file saved in /etc/X11/xinit/xinitrc in Arch XFCE
## (shell-command "cp ~/config_github/app/xorg_X11/etc_X11_xinit_xinitrc /etc/X11/xinit/xinitrc") 
## common system conf
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

## [TODO] if 또는 case 문으로 uname으로 다른 OS 간의 사용을
##        자동으로 통합하는 것을 고려해 볼 것도 가능할 것이다.
### user system conf
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi


if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi



# start some nice programs
## here 폴더 내에서 기본으로 실행을 지정할 수 있는 것으로 보인다.
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
# unset CMD는 변수를 해소하는 것으로 추정된다.

twm & # 여기에 twm의 기본실행이 나오므로 FreeBSD에서 다른 것으로 변경하면 될 것으로 보인다. 기존
# pkill twm && dwm & 의 명령을 실행하고 있었다.
xclock -geometry 50x50-1+1 &
xterm -geometry 80x50+494+51 &
xterm -geometry 80x20+494-0 &
exec xterm -geometry 80x66+0+0 -name login
## (shell-command "cp /etc/X11/xinit/xinitrc ~/config_github/app/xorg_X11/etc_X11_xinit_xinitrc") 
 
