# (progn (save-buffer)(shell-command "/home/thinkpad/.bin/grasp/server/grasp_server.py --path /home/thinkpad/config_github/great_books/_achieve_agenda/2019_11_diary.org"))
#+START: overview
#+start: show_all
#+TAGS: org_diary(d) todo(t)

#+BEGIN_SRC text
sdkf
sdf
sf
s
f
sdf
*




#+END_SRC

#+BEGIN_TEXT python
echo hi
print("hi")

#+END_TEXT

#+NAME: e_text
#+BEGIN_TEXT sh
(dired-jump good day in the world is best place
echo hi
#+END_TEXT

#+BEGIN_SRC sh :var a=e_text :results raw replace
while true ; do
echo 1
espeak "$a"
echo 2
sleep 30
done
#+END_SRC


#+RESULTS:
#+BEGIN_SRC sh :var a=greek_tex
notify-send -t 3000 "hi
$a
"
#+END_SRC

#+RESULTS:


#+BEGIN_SRC org
|
 sdf|asdf|asdf|
|asdf|asdf|Asdfa|
[[file:/][sdf]]
[[file://][hi]]


#+END_SRC
#+BEGIN_text markdown
# 제목이 나온다.
## 크기는 같다. 그러나 진하게 bold
### wow markdown
[asdf](sdf)

[2019-11-01 Fri 11:00]
- gi dow
* 
__slant 기울어진__
**굵은 글씨bold **
#+END_text


#+BEGIN_SRC org

[2019-11-01 Fri]

#+END_SRC
* [2019-11-01 Fri] 

- An Introduction To Programming In Emacs Lisp
(shell-command "xdg-open \"$HOME/Documents/An Introduction To Programming In Emacs Lisp, 2Nd Ed - Robert J. Chassell.pdf\"")
<2019-11-01 Fri 11:00>
Go 024 상징:Symbol is a way of locating the definition or set of instructions.
자신의 이름역시 상징에 불과하며 그 이면에 내재하는 깊은 본질을 탐구하는 것은 드물다.
  # In Lisp, both data and programs are represented the same way;
  # (Since a program looks like data, one program may easily serve as data for another; 
        # this is a very powerful feature of Lisp.) 버그와 해킹의 중간영역은 매우 방대하다.
'Lots of Isolated Silly Parentheses' LISt Processing
Atom unsplittable in Lisp, 
A list in Lisp -any list- is a program ready to run. (Lisp jargon is evaluate)
Run(evaluate) list do one of 3 thing( return list itself; send error message; treat first symbol as command-instruction to do something)
single apostrophe, ', that quote , do nothing with the list, other than take it as it is written.

list is consists  of parentheses surrounding atoms separated by whitespace or surrounding tothe rlists or surrounding both atoms and other lists.

岀力된 表現, 원자와 리스트는 像徵된 式이라고 불린다.
printed representation of both atoms and lists are called symbolic expressions or, more concisely, s-expressions.
expression itself can refer to either the printed representation, or to the atom or list as it is held internally in the computer.
symbolic expressions, s-expressions
one set of instructions can be attached to several names.
On the other hand, a symbol can have only one function definition attached to ti at a time.
함수가 속한 부분을 표시하는 형식으로 함수명이 정해진다. 
#+BEGIN_SRC emacs-lisp
(setq a '(+ 0 1)
      b (quote (+ 0 1 1)))

(+ 1 (eval a))
;(+ 1 (eval b))
#+END_SRC

#+RESULTS:
: 2

먼저, '를 확인하고 계산한다. 결과 도출 또는 에러메시지.
계산 Evaluation-'to ascertain the value or amount of; to appraise' activity of works on an expression
interpreter 'evaluates the expression'. Return a Value.
( + 1 2)  fill-column \a #o23457 #x0Fa \t \n "안녕하세요 이것도 계산문장이돠."  ;; 이러한 다양한 표현도  C-x C-e eval-last-expression으로 계산됨.
요약: 리스트를 구성하는 아톰은  상징과 숫자 문자열을 포함. (상징)식은 계산된다. 상징은 함수, 값, 혹은 둘다를 가질 수 있다

(setq + 3)  (eval (quote (+ 2 +)))
(substring "123" 0 3) substring substring is A function such as substring uses both a string and numbers as arguments. 
(*) => 'evaluates to'
 because every Lisp function must return a value if it does not get an error, 
but it will only have a side effect if it is designed to have one.
G 038에있는 종합은 걸작이다.

interactive functions, or commands : The functions you
evaluate by typing keystrokes are called interactive functions, or commands;
모든 키의 입력역시 식의 계산이며 그 첫 요소는 함수이다. self-insert-command가 키의 누름시 함수다.

A name and the object or entity to which the name refers are different
from each other. You are not your name. You are a person to whom others
refer by name. 
You do not want to speak to the
name, but to the person to whom the name refers.
이름은  그 뒤에 위에 숨은 본질에 접근하는 방편이다. 언어는 도단이다.
The choice of name is up to the programmer and should be chosen
to make the meaning of the function clear.
이름의 선택은 기능을 명확히 하는 수단이다.
1
2
5
3
jj;

(+)(buffer-name)"2019_11_diary.org"
(buffer-file-name)"/home/thinkpad/config_github/great_books/_achieve_agenda/2019_11_diary.org"
"2019_11_diary.org" "2019_11_diary.org""/home/thinkpad/config_github/great_books/_achieve_agenda/2019_11_diary.org"
C-u C-x C-e 출력이 나오다. 버퍼에 또한  C-u M-x (buffer-file-name)
"/home/thinkpad/config_github/great_books/_achieve_agenda/2019_11_diary.org"
"/home/thinkpad/config_github/great_books/_achieve_agenda/2019_11_diary.org"

2
hi
1
a
(defun multiply-by-3 (number) ;
"Multiply Number by 3."
(interactive "p")
(message "The result is %d" (* 3 number)))

3
(multiply-by-3 3)"The result is 9"
(if (equal 'hi 'hi)
	(message "3 is greater than 2"))

(defun type-of-animal (characteristic)
"Print message in echo area depenidng on CHARACTERISTIC.
If the CHARACTERISTIC is the symbol 'fierce',
then warn of a tiger."
(if (equal characteristic 'fierce)
    (message "It's a tiger!")))
(type-of-animal 'fierce) ;only symbol is work true.


Lisp interpreter is concerned, () and nil are the same.
Humans, however, tend to use nil for false and () for the empty list
사람의 경우 구분을 해서 인식할 필요가 있다.

[Emacs Lisp Basics](http://ergoemacs.org/emacs/elisp_basics.html) 중국계의 놀라운 자료실 공부방으로 중요함.


*** DONE 이전의 노트한 것을 옮긴다.
리: "/home/thinkpad/config_github/app/emacs/spacemacs/analysis/kbd/readme.org"
M-| 또는 C-u M-| 
M-g M-g 또는 g 줄로 이동하기 
M-x view-lossage ;;입력의 기록을 보는 것임. 검색해서 실시간을 찾아볼것.
C-; comment가 아니라 iedit.el로 설정되어 있음. 동시변환의 기능으로 영역설정후 원하는 것 일괄동시 변경함.
cua-mode연구필요함.
abcdefg


#+BEGIN_SRC emacs-lisp
(ding) (beep)

#+END_SRC

* [2019-11-02 Sat] 
  - 

*** DONE 다이어리(발생이력), 발달(활용처, 원리연구처)
초기와 발달을 이해하면 전체를 알 수 있다. 아리스토텔레스
인: [시간] - 
리:
사:  
연:

*** DONE [2019-11-02 Sat 15:18] gentoo route CMD 발견
[7 Linux Route Command Examples (How to Add Route in Linux)](https://www.thegeekstuff.com/2012/04/route-examples/)
정답은 # route add default gw 192.168.123.254 
인: gentoo에서 wifi와 ethernet의 라우터 충돌발생 [2019-11-02 Sat 15:18]
리: ssh/route_cmd.org (find-file-other-window "~/config_github/app/ssh/route_cmd.org")
- 파일 이치적인 파일
route add 10.236.11.0 mask 255.255.255.0 10.236.10.1
사: gentoo_lfs
- 파일 활용적인 파일
연: (find-file-other-window "~/config_github/os/gentoo/install_process/youtube_t530_study.org")
 


*** DONE Wishlist:   # 좋은 방법론
인: [2019-11-02 Sat] 겐투검색하다 맥북에서 동영상 발견
리: 1.org_meta_method 2.search_find/awk
사: 겐투 xsetroot_bar_info in start CMD
연:
         - Show Memory Used/Total
free -h | awk '/^Mem:/ {print $3 "/" $2}'
         - Show CPU Temp
sensors | awk '/^fan/ {getline; print $2}'
         - Show most Memory intensive processes

         - Show most CPU intensive processes
Then create status bar module for CPU/Mem.

sudo pacman -S lm_sensors
awk next line method
awk '/C02/{print;getline;print}' ~/temp/log.txt

*** DONE (find-file-other-window "/home/thinkpad/config_github/app/emacs/search_find_grep_emacs.org")
#이곳을 검색의 중심지로 사용한다.

* [2019-11-03 Sun]
*** ediff-regions-wordwise 영역비교에 놀라운 기능을 발견함.
ediff-regions-wordwise
ediff-merge-buffers
 diff-buffer-with-file. Wish ediff could do that.
M-x ediff-current-file

 '(ediff-split-window-function (quote split-window-horizontally))
 '(ediff-window-setup-function (quote ediff-setup-windows-plain))

M-x compare-windows (and C-x z z z z ... to repeat as necessary).
*** say_greek say_latin in .bin/
- 엄정한 것은 깊은 통찰을 요구한다.
* [2019-11-04 Mon] 
- thinkpad W541 lot of 2 purchase!!! $395
* [2019-11-05 Tue] 

		(find-file-other-window "~/config_github/app/emacs/org_mode_study/")
- defalias for elisp(py) in babel 출처:elisp_emacs_lisp_babel_defalias.org
- BEGIN_SRC emacs-lisp :results value :results raw :exports results 출처:babel_exports_results_form.org
- agenda C-c [ 리스트에 추가하는 방식을 연구함.  C-c / t ;;현재 폴더내의 투두만 국한 -
    - /emacs/org_mode_study/agenda_view_org.org

(require 'org-plus-contrib)
* [2019-11-07 Thu]
- 아침에 전원이 꺼져서 시도한 stumpwm에서 놀라운 정적인 것의 유용함을 발견함.
- 높은 통합성과 
	- 

	#+BEGIN_SRC sh
	  echo "실행이 C-M-x 로 org내에서 C-c C-'에서 가능함을 확인함."
	#+END_SRC

tace




** (compile-file "hello.lisp") stumpWM의 화면띄우기의 통합을 위한 조치.
#+BEGIN_SRC common-lisp
(compile-file "hello.lisp")
(load "hello.fasl")
;;or
(load (compile-file "hello.lisp"))
#+END_SRC
* [2019-11-08 Fri]

;echo hi
(message "hi world")
"hi world";;;good ayd
#+BEGIN_SRC sh
  echo hi


#+END_SRC
** note from FreeBSD
You can use aliases to decrease the amount of typing you need to do to get
commands you commonly use.  Examples of fairly popular aliases include (in
Bourne shell style, as in /bin/sh, bash, ksh, and zsh):

	alias lf="ls -FA"
	alias ll="ls -lA"
	alias su="su -m"

In csh or tcsh, these would be

	alias lf ls -FA
	alias ll ls -lA
	alias su su -m

To remove an alias, you can usually use 'unalias aliasname'.  To list all
aliases, you can usually type just 'alias'.

Want to list all files of an installed package? Enter                                              │··················································
"pkg info -l packagename". 


- cp -a source target
If you want to recursively copy a directory preserving file and directory
attributes use
"cp -a source target"

		-- Lars Engels <lme@FreeBSD.org>

** save before python link

** ssh -X thinkpad@FreeBSD.local # good Discovery
** package install slime
save: /computer_language/commonlisp_closure/
save:emas/download paedit with swack

;; closure https://youtu.be/O9M-c6UrOyE?t=82
CCL is Clojure's Common Lisp
? (load "/emacs-local/slime/swank-loader.lisp")
? (swank-loader:init)
? (swank:create-server :dont-close t)

;; install (package-list-packages 'clojure-mode)
(unless (package-installed-p 'clojure-mode)
  (package-install 'clojure-mode))



(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(package-refresh-contents)

;;아래는 이맥스 내부에서 
M-x slime-connect 127.0.0.1        port: 4005
잘 안되는 것 같음.

(defun hello-world (msg) (format t "Hello world, hello ~A~%" msg) )
(hello-world "kami") 

버그와 해킹의 경계가 불완전하다.
** slime (setq inferior-lisp-program "/usr/bin/sbcl")
(setq slime-contribs '(slime-fancy))
(require 'slime)
* Todo꼭!매일 

* TODAY_DONE_ 

* 임의적인 입력의 노트 
[2019-11-02 Sat 10:33]


#+NAME: test1
#+BEGIN_SRC sh :results raw
espeak "hi23"
echo "hi123"
#+END_SRC

#+RESULTS: test1





#+call: test
#+call: test1
#+BEGIN_SRC org
;; 
[[asdfs][sdfsdf]] echo 2
call_test1()
#+END_SRC

#+RESULTS:


hi
hi2
hi



* test

* how to grasp in Chrome
* C-x C-s먼저! 
* (progn (save-buffer)(push-mark-command 1)(end-of-buffer)(shell-command "/home/thinkpad/.bin/grasp/server/grasp_server.py --path /home/thinkpad/config_github/great_books/_achieve_agenda/2019_11_diary.org"))
* (revert-buffer)

* Tasks
* [2019-11-08 Fri 19:30] Emacs CL part 2 (G101, video 2) - YouTube :grasp:
https://www.youtube.com/watch?v=w4MCEaK072I

* [2019-11-08 Fri 19:31] Emacs CL part 2 (G101, video 2) - YouTube :grasp:
https://www.youtube.com/watch?v=w4MCEaK072I
* [2019-11-08 Fri 19:33] Emacs CL part 2 (G101, video 2) - YouTube    :grasp:
https://www.youtube.com/watch?v=w4MCEaK072I

* [2019-11-08 Fri 19:38] Moving Point - GNU Emacs Manual :grasp:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-Point.html

this is test
* [2019-11-08 Fri 19:50] (push-mark-command 1)을 사용함.(set-mark 1)이 잘 안되서 우회함.elisp - How do I set key binding for set mark in emacs? - Unix & Linux Stack Exchange :grasp:
https://unix.stackexchange.com/questions/91834/how-do-i-set-key-binding-for-set-mark-in-emacs
Selection:
You need to pass your arguments to push-mark, not global-set-key:

(global-set-key (kbd "M-SPC") (lambda() (interactive) (push-mark nil nil 1)))
* [2019-11-08 Fri 20:11] Regions, marks, and visible-mark | Pragmatic Emacs :grasp:
http://pragmaticemacs.com/emacs/regions-marks-and-visual-mark/
Selection:
C-u C-SPACE to jump around the previous marks
gitlab_visible_mark_chrome_grasp.org
* [2019-11-08 Fri 21:17] '최고 등급' 수배자 윤지오.."편파수사" 강력 반발 | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191108200407667
Selection:
최근들어 확실하게 느낄수있는건
대한민국 경찰,검찰은 
기득권들과 더러운 권력자,재력가들에게 만큼은
절대 수사하지 않고
오로지 만만하거나 약자들에게만 철퇴를 휘두른다!
* [2019-11-08 Fri 21:33] 정부, '엽기 살인현장' 北선박 공개.."北에 인계 완료"(종합2보) | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191108185951555?d=y
Selection:
토착왜구들이 본래 기준없이 정부 까는데 급급한 말종집단들이라서 반대경우엔 살인범들 받아들였다고 짖어댈건 뻔한 반응...
* [2019-11-08 Fri 21:34] 김성태 딸 "정규직 공채 직접 지원..퇴근후 시험준비"(종합) | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191108193808219?d=y
Selection:
딸이 피의자 아니고 증인이여? 성태는 막봐주네 정치인인데도 비공개소환하고. 나경원이는 언제수사하냐? ㅉㅉ
참으로 가증스럽다.
그토록 많은 증거가 있건만 끝까지...
* [2019-11-08 Fri 21:46] 긴장한 채 잔뜩 허리 굽힌 尹..'조국 정국' 후 文대통령 첫 대면 | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191108163222695?d=y
Selection:
문재인 대통령 하시는 언행을 보면, 사는 동안 남자의 세계라는 게 무엇인지를 깨닫게 하는 표본이라고 본다.
회초리 들어야 할 때와 은은한 듯 강렬한 눈빛으로 묵언의 깨우침을 가지게 해야  할 때를 시의적적하게 판단하신다.

참 대단한 분이시다.
그러므로 우리 문프를 존경하지 않을 수가 없다. 나의 대통령 문재인!!
* [2019-11-08 Fri 21:46] 8년간 겉만 살짝 긁어낸 日..비만 와도 방사능 '쑥' | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191108200717722?d=y
Selection:
그린피스] "(재)오염이 실제로 될 수밖에 없다는 걸 현실에서 보고나니까 정말 이 재앙은 지금 시작에 불과하구나 라는 절망감이 들었습니다."
* [2019-11-08 Fri 21:47] How to move forward and backward in Emacs' mark ring - Stack Overflow :grasp:
https://stackoverflow.com/questions/3393834/how-to-move-forward-and-backward-in-emacs-mark-ring

* [2019-11-09 Sat 07:35] neotree
(defun neotree-open-file-in-system-application ()
  "Open a file under point in the system application."
  (interactive)
  (call-process neo-default-system-application nil 0 nil
                (neo-buffer--get-filename-current-line)))

(defun neotree-open-file-in-system-application ()
  "Open a file under point in the system application."
  (interactive)
  (call-process neo-default-system-application nil 0 nil
                "/home/thinkpad/Music/Gentoo Install Guide 4_5-ZiO75hTbs7w.mkv")


)
* [2019-11-09 Sat 07:53]C-h ? l keyboard stroke history!!!
* [2019-11-09 Sat 13:28] 모친 삼우제 불참한 文대통령, 어젯밤 양산 묘소 방문 | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191109123354651?d=y

* [2019-11-09 Sat 13:28] 심상정 "이자스민, 黃 '임금차별' 논란에 당 정리 고민..입당 적극 권유" | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191109102116263?d=y

* [2019-11-09 Sat 13:28] '주사파 발언' 박홍 전 서강대 총장 선종(종합) | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191109102853358?d=y
Selection:
 "고백성사를 하러 온 학생들로부터 들었다"고 해명했지만 신도들로부터 고백성사 누설 혐의로 고발당했다. 천주교 사제가 신도로부터 고발당하기는 처음 있는 일이었다.
* [2019-11-09 Sat 13:29] '전두환 골프' 덮친 임한솔 부대표가 밝힌 당일 취재기록.."너 명함 있냐?" | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191109105554671?d=y
Selection:
“기력이 없으세요”

▲임한솔

“기력이 없는데 어떻게 골프를 치고 계세요? 광주 518 학살에 대해서 한 말씀해주시죠”

▲전두환

“광주학살에 대해서 모른다 나는.”
* [2019-11-09 Sat 13:29] 檢, 정경심 조사 사실상 마무리..조국 동생 구치소 병동에 '입원' | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191109114201172
Selection:
사흘 연속 건강 문제를 이유로 불출석 사유서를 내고 검찰 조사에 출석하지 않았습니다.

조 씨 측은 현재 목 부위 신경 통증으로 구치소 내 병동에 입원했다
* [2019-11-09 Sat 13:30] 공무원·군인연금 눈덩이 부채 940조..정부 개혁안 검토 | Daum 뉴스 :grasp:
https://news.v.daum.net/v/20191109110019714
Selection:
연금부채, 2015년 660조→2018년 940조

앞서 기재부가 발표한 ‘2018회계연도 국가결산’에 따르면 연금충당부채(공무원연금부채+군인연금부채)가 지난해 연금충당부채가 939조9000억원에 달했다. 이는 국가부채(재무제표 기준 1682조7000억원)의 55.8%에 달하는 규모다. 


* bwi Broadcom ipw iwn interl wireless WiFi
* sudo kldload iwm7260fw 일단 작동됨.
* sudo kldload iwm7265Dfw 일단 작동됨.


* sudo kldload iwm7265fw 일단 작동됨.
* sudo kldload if_bwi 일단 작동됨.
* work list show in BSD $ kldconfig -r
* kldstat | grep iw # 매우 좋은 결과!!!!
* #  sudo pciconf -lbcev | less # 핵심broadcom!
bwn_pci0@pci0:3:0:0:    class=0x028000 card=0x000d1028 chip=0x432b14e4 rev=0x01 hdr=0x00
    vendor     = 'Broadcom Inc. and subsidiaries'
    device     = 'BCM4322 802.11a/b/g/n Wireless LAN Controller'
    class      = network
    bar   [10] = type Memory, range 64, base 0xf2400000, size 16384, enabled
    cap 01[40] = powerspec 3  supports D0 D1 D2 D3  current D0
    cap 09[58] = vendor (length 120)
    cap 05[e8] = MSI supports 1 message, 64 bit 
    cap 10[d0] = PCI-Express 1 endpoint max data 128(128)
                 link x1(x1) speed 2.5(2.5) ASPM L0s/L1(L0s/L1)
    ecap 0001[100] = AER 1 0 fatal 0 non-fatal 0 corrected
    ecap 0002[13c] = VC 1 max VC0
    ecap 0003[160] = Serial 1 be492cffff200024
    ecap 0004[16c] = Power Budgeting 1

* dmesg | grep iw # 더좋은 결과 iwn0  <Intel Centrino Advancde N 6205>
* 일단 참고명령 # service netif restart
* 일단 참고명령 # ifconfig 
* 일단 참고명령 # ifconfig wlan0 up scan
* # options BWN_GPL_PHY
bwn0: bwn_phy_n_attach: BWN_GPL_PHY not in kernel config; no PHY-N support
bwn0: failed
$$$$$$$$$
bwn_v4_ucode_load="YES"
bwn_v4_n_ucode_load="YES"
if_bwn_load="YES"

* (clover) sudo make menuconfig - [*] 추가함! Support for N-PHY (the main 802.11n series) devices
cd /usr/src/linux ; sudo make menuconfig 
  .config - Linux/x86 5.2.16-gentoo Kernel Configuration                                                  │·······································································································································································
 → Device Drivers → Network device support → Wireless LAN
https://youtu.be/C-Np_IOImqU?t=714 pdf linux kernel in nutshell

* # (clover)(인스톨) # sudo genkernel --install initramfs #https://youtu.be/C-Np_IOImqU?t=1355
BroadCom
[    8.659609] b43-phy0: Broadcom 4322 WLAN found (core revision 16)
[    8.684738] snd_hda_intel 0000:00:1b.0: bound 0000:00:02.0 (ops i915_audio_component_bind_ops [i915])
[    8.685103] input: Wacom ISDv4 E6 Finger as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.5/2-1.5:1.1/0003:056A:00E6.0002/input/input23
[    8.685371] wacom 0003:056A:00E6.0002: hidraw1: USB HID v1.11 Mouse [Tablet ISD-V4] on usb-0000:00:1d.0-1.5/input1
[    8.699502] snd_hda_codec_conexant hdaudioC0D0: CX20590: BIOS auto-probing.
[    8.699965] snd_hda_codec_conexant hdaudioC0D0: autoconfig for CX20590: line_outs=1 (0x1f/0x0/0x0/0x0/0x0) type:speaker
[    8.699967] snd_hda_codec_conexant hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    8.699968] snd_hda_codec_conexant hdaudioC0D0:    hp_outs=2 (0x1c/0x19/0x0/0x0/0x0)
[    8.699969] snd_hda_codec_conexant hdaudioC0D0:    mono: mono_out=0x0
[    8.699969] snd_hda_codec_conexant hdaudioC0D0:    inputs:
[    8.699971] snd_hda_codec_conexant hdaudioC0D0:      Internal Mic=0x23
[    8.699972] snd_hda_codec_conexant hdaudioC0D0:      Mic=0x1b
[    8.699972] snd_hda_codec_conexant hdaudioC0D0:      Dock Mic=0x1a
[    8.700526] b43-phy0: Found PHY: Analog 8, Type 4 (N), Revision 4
[    8.700574] b43-phy0: Found Radio: Manuf 0x17F, ID 0x2056, Revision 3, Version 0
[    8.701690] snd_hda_codec_conexant hdaudioC0D0: Enable sync_write for stable communication
[    8.713256] input: HDA Intel PCH Mic as /devices/pci0000:00/0000:00:1b.0/sound/card0/input25
[    8.713323] input: HDA Intel PCH Dock Mic as /devices/pci0000:00/0000:00:1b.0/sound/card0/input26
[    8.713377] input: HDA Intel PCH Dock Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card0/input27
[    8.713433] input: HDA Intel PCH Headphone as /devices/pci0000:00/0000:00:1b.0/sound/card0/input28
[    8.713488] input: HDA Intel PCH HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1b.0/sound/card0/input29
[    8.713542] input: HDA Intel PCH HDMI/DP,pcm=7 as /devices/pci0000:00/0000:00:1b.0/sound/card0/input30
[    8.713592] input: HDA Intel PCH HDMI/DP,pcm=8 as /devices/pci0000:00/0000:00:1b.0/sound/card0/input31
[    8.720719] Broadcom 43xx driver loaded [ Features: PNLS ]
[    8.720874] ssb0:0: Missing Free firmware (non-Free firmware loading is disabled)
[    8.724939] b43 ssb0:0: Direct firmware load for /*(DEBLOBBED)*/ failed with error -2
[    8.724941] b43 ssb0:0: Falling back to syfs fallback for: /*(DEBLOBBED)*/
[    9.170716] ssb0:0: Missing Free firmware (non-Free firmware loading is disabled)
[    9.176381] ssb0:0: Missing Free firmware (non-Free firmware loading is disabled)
[    9.176441] b43 ssb0:0: Direct firmware load for /*(DEBLOBBED)*/ failed with error -2
[    9.176443] b43 ssb0:0: Falling back to syfs fallback for: /*(DEBLOBBED)*/
[    9.188379] ssb0:0: Missing Free firmware (non-Free firmware loading is disabled)
[    9.196377] b43-phy0 ERROR: Firmware file "/*(DEBLOBBED)*/" request failed (err=-11)
[    9.196378] b43-phy0 ERROR: Firmware file "b43-open//*(DEBLOBBED)*/.fw" request failed (err=-11)
[    9.196379] b43-phy0 ERROR: /*(DEBLOBBED)*/

* # (clover) before install kernel (with Intel Corporation Centrino)
$ lspci -kv
03:00.0 Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
        Subsystem: Intel Corporation Centrino Advanced-N 6205 (802.11a/b/g/n)
        Flags: fast devsel, IRQ 17
        Memory at f2400000 (64-bit, non-prefetchable) [size=8K]
        Capabilities: <access denied>
        Kernel modules: iwlwifi
$ dmesg | grep iw                                                                                                                                  
[   12.685390] iwlwifi 0000:03:00.0: can't disable ASPM; OS doesn't have ASPM control                                                                                   
[   12.686326] iwlwifi 0000:03:00.0: Direct firmware load for /*(DEBLOBBED)*/ failed with error -2                                                                      
[   12.686328] iwlwifi 0000:03:00.0: Falling back to syfs fallback for: /*(DEBLOBBED)*/                                                                                 
[   12.692848] iwlwifi 0000:03:00.0: Direct firmware load for /*(DEBLOBBED)*/ failed with error -2                                                                      
[   12.692849] iwlwifi 0000:03:00.0: Falling back to syfs fallback for: /*(DEBLOBBED)*/                                                                                 
[   12.700851] iwlwifi 0000:03:00.0: no suitable firmware found!                                                                                                        
[   12.700854] iwlwifi 0000:03:00.0: minimum version required: /*(DEBLOBBED)*/5                                                                                         
[   12.700855] iwlwifi 0000:03:00.0: maximum version supported: /*(DEBLOBBED)*/6                                                                                        
[   12.700856] iwlwifi 0000:03:00.0: check /*(DEBLOBBED)*/ 



* # (clover) sudo make menuconfig
03:00.0 Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
        Subsystem: Intel Corporation Centrino Advanced-N 6205 (802.11a/b/g/n)
        Flags: fast devsel, IRQ 17
        Memory at f2400000 (64-bit, non-prefetchable) [size=8K]
        Capabilities: <access denied>
        Kernel modules: iwlwifi

 $ dmesg | grep iw                                                                                                                                  
[   12.355563] iwlwifi 0000:03:00.0: can't disable ASPM; OS doesn't have ASPM control                                                                                   
[   12.355838] iwlwifi 0000:03:00.0: Direct firmware load for /*(DEBLOBBED)*/ failed with error -2                                                                      
[   12.355840] iwlwifi 0000:03:00.0: Falling back to syfs fallback for: /*(DEBLOBBED)*/                                                                                 
[   12.361064] iwlwifi 0000:03:00.0: Direct firmware load for /*(DEBLOBBED)*/ failed with error -2                                                                      
[   12.361066] iwlwifi 0000:03:00.0: Falling back to syfs fallback for: /*(DEBLOBBED)*/                                                                                 
[   12.369055] iwlwifi 0000:03:00.0: no suitable firmware found!                                                                                                        
[   12.369057] iwlwifi 0000:03:00.0: minimum version required: /*(DEBLOBBED)*/5                                                                                         
[   12.369058] iwlwifi 0000:03:00.0: maximum version supported: /*(DEBLOBBED)*/6                                                                                        
[   12.369060] iwlwifi 0000:03:00.0: check /*(DEBLOBBED)*/                                                                                                              


 $ sudo fwts aspm   



* [2019-11-09 Sat 19:48] freebsd/if_bwn_phy_n.c at master · freebsd/freebsd :grasp:
https://github.com/freebsd/freebsd/blob/master/sys/dev/bwn/if_bwn_phy_n.c
Selection:
freebsd/sys/dev/bwn/if_bwn_phy_n.c
Find fileCopy path


* 일단 참고명령 # dmesg | grep bwn
bwn_pci0: <Broadcom BCM4322 802.11n Dual-Band Wireless> mem 0xf2400000-0xf2403fff irq 17 at device 0.0 on pci1
bhndb0: <PCI-BHND bridge> on bwn_pci0
bhndb0: Using MSI interrupts on bwn_pci0
bwn0: <Broadcom 802.11 MAC/PHY/Radio, rev 16> mem 0x18001000-0x18001dff,0x18001f00-0x18001fff,0x18001e00-0x18001eff irq 1 at core 1 on bhnd0
bwn0: bwn_phy_n_attach: BWN_GPL_PHY not in kernel config; no PHY-N support
* 일단 참고명령 # wpa_supplicant -D bsd -i wlan0 -c /etc/wpa.conf -B
* sudo ifconfig wlan0 create wlandev iwn0 # ifconfig에 wlan0 출현!!!!!!
* ifconfig wlan0 scan # 매우 잘 탐색함.

$  ifconfig wlan0 scan
SSID/MESH ID                      BSSID              CHAN RATE    S:N     INT CAPS
ollehEgg_014                      00:1d:93:81:d1:d6    1   54M  -81:-95   100 EPS  HTCAP RSN WPA WME
Public WiFi Free                  02:06:ac:80:26:c6    5   54M  -74:-95   100 ES   HTCAP WME ATH
Public WiFi FREE                  12:06:ac:80:26:c6    5   54M  -74:-95   100 ES   HTCAP WME ATH
U+NetE62C                         18:c5:01:a1:e6:2e    5   54M  -91:-95   100 EPS  HTCAP VHTCAP VHTOPMODE WME ATH RSN
$  ifconfig wlan0 scan
SSID/MESH ID                      BSSID              CHAN RATE    S:N     INT CAPS
U+NetA19B                         18:c5:01:8a:a1:9a   11   54M  -89:-95   100 EP   HTCAP RSN WME
Public WiFi Free                  02:06:ac:80:26:c6    5   54M  -74:-95   100 ES   HTCAP WME ATH
Public WiFi Free                  02:06:ac:80:26:c2    5   54M  -90:-95   100 ES   HTCAP WME ATH
$ dmesg | grep iw
module iwi already present!
iwn0: <Intel Centrino Advanced-N 6205> mem 0xf2400000-0xf2401fff irq 17 at device 0.0 on pci1
iwn0: iwn_read_firmware: ucode rev=0x12a80601
iwn0: iwn_read_firmware: ucode rev=0x12a80601
iwn0: iwn_read_firmware: ucode rev=0x12a80601
module iwi already present!







SSID/MESH ID           BSSID
Public WiFi FREE       12:06:ac:80:26:c6
Public WiFi FREE       12:06:ac:80:26:c2

ctrl_interface=DIR=/run/wpa_supplicant GROUP=wheel
update_config=1
country=kr
country=us
update_config=1
ctrl_interface=/var/run/wpa_supplicant

########refer#########
wpa_suplicant.conf
Code:
ctrl_interface=/var/run/wpa_supplicant
update_config=1
ap_scan=1
fast_reauth=1

network={
    ssid="ssid"
    psk="password"
}


rc.conf
Code:
ifconfig_bce2_name="wlan0"        # External Network
ifconfig_wlan0="WPA DHCP"


########refer#########


* note3.org To see the last time that you logged in, use lastlogin(8)
* net-setup wlan0 in Gentoo but 
* [2019-11-10 Sun 08:46] emacs newbie question - how to search within a region - Stack Overflow :grasp:
https://stackoverflow.com/questions/1893795/emacs-newbie-question-how-to-search-within-a-region#1893817
Selection:
You can use this combination of commands:

M-x narrow-to-region
C-s SOMETEXT
M-x widen
C-x n n
C-s sometext
C-x n w


(shell-command-to-string "echo -test! $x-")"-test! -
"


1
ab
2
12
123

* [2019-11-10 Sun 09:24] How to find file by inode number » Linux Ask! | Linux Ask! :grasp:
http://www.linuxask.com/questions/how-to-find-file-by-inode-number
Selection:
To find a file by its inode number, you can use the argument -inum with the find command. e.g.

# find -inum 8232976
./test.txt
./hard_link.txt
* [2019-11-10 Sun 09:28]  okular "$(find ~/Music  -inum 6836311)" & c - How can I access file by inode on Linux - Stack Overflow :grasp:
https://stackoverflow.com/questions/31428641/how-can-i-access-file-by-inode-on-linux/31432662#31432662
Selection:
2

I found the question connected concerning similar topic here.

Summarizing, check out those commands:

find /path/to/mountpoint -inum <inode number>
sudo debugfs -R 'ncheck 393094' /dev/sdaX 2>/dev/null
* [2019-11-11 Mon 13:18] route -n ip r
Run command: 참조 /app/ssh/route.org
$ route add default gw {IP-ADDRESS} {INTERFACE-NAME}
$ route add default gw 192.168.2.254 eth0

* [2019-11-11 Mon 13:18]  qt.qpa.xcb: could not connect to display localhost:10:0


* [2019-11-12 Tue]
** 
* [2019-11-14 Thu] 138-4 138-5 우리땅
136 영감님 땅 180평 400평
* [2019-11-15 Fri] 
* [2019-11-16 Sat]
* 무의히한 건축의 놀이들 무의미한 맘기의 향연에서 무엇이 남나가?? 자유냐 공허냐 ?
교육청의 돈 못먹는 놈이 바보라는 식의 사고방식-학생수 줄어도 예산은 더 타다가 땅에 쳐박음.

무의미한 말폭탄을 종료시키는 좋은 방법은 그냥 내버려두면 저절로 처박다가 멈춘다는 것이다.

유태인들은 중요한 거래는 계약서 없이 이루어진다고 한다. 전세계 다이아몬드 소각권이 그들에게.
그리고 한사람 건너면 전부 연결된다는 단단한 인적네트워크.

666의 실체는 전통이라고 불리며, 관행이라는 관료제며, 권위라고하는 사기라고 생각한다.
무지를 배경으로 남을 기만하고 자신도 함정에 빠지는 무책임한 사실에 대하여 
자유의 깃치를 높이 들어올린다.
약인욕료지 삼세일체불 응관법계성 일체유심조!
자아는 인류의 가장큰 발견과 발굴의 대상이다 그 무한의 실체가 법성이며 진리이며 하느님이다.
일체유위법 여몽환포영 여로역여전 응작여시관

놀라운 그들의 세상에 가고 싶고 함께 느끼며 공부하고 싶다. 짐승적인 무의미의 암기의 세계를 넘어서서.
수학의 놀라운 통일성과 불가해성... 그리고 인간 이성의 놀라운 경이로운 신비.에 감탄을 느낀다.


[2019-11-16 Sat 15:45] 거짓말로 사람을 속이는 자는 자아의 힘을 박탈당하고 천벌을 받는다.


남의 돈이 정말 무서운 것을 알았습니다. 
주말에 거래하는 것이 아니라 은행문 열려있는 때 거래해야 하는 것을 알았습니다.



- 농협의 직원부탁
친필확인나중에 감정요청
개인정보 주민증사진의 폐기 요구를 할 수 있는지. 문의.


기억나는 장면.
이정임이라는 거짓말하는 여자의 뻔뻔한 헛웃음 

은인의 등을 치려는 자의 어리석음. 깊은 수렁의 느낌. 계약위반으로 800만원이 아니냐는 식.



부동산거래에서 배운 점 
- 전화거래시 중요부분은 확실히 녹음하도록 준비할 것.
-  !절대로 꼭! 직접 만나보고 대화하고 일일히 대장등기 꼭! 확인해 볼 것.
   - 믿으라고 강요해도 속으면 안됩니다.

- # 큰돈 거래시 꼭 건장하고 말주변있는 주변인 3, 4명 동행할 것. 중요한 부분에 녹음기 갖고 녹음할 것.
- # 경찰서 민원실에 들어가서 물어볼 것. 사정이야기 하고. 

- 사기꾼은 3인 1조의 형태로 구성되는 경우, 소장(잘모르쇠), 2번째(간보면서, 약점탐색), 3번째는(자기유리주장)
      - 본질에 집중할 것. 항상 꼬투리잡아서 말자르고 
	승냥이무리처럼 먹이감을 3명이서 돌아가면서 뒤흔들어서 공략합니다. 자기들 유리한 주장으로 몰아감.
- 사고처리시 빠른 증거나 진술서 확보를 해 둘 것.


오호라! 사람의 믿음이 중요하고 서로간의 신뢰가 중요하건만 
부동산 전문가랍시고 믿으해 놓고 나중에 기만합니다.
분해고 억울하면,미리미리 준비하는 것이 현명하다는 것을 깨달음.

 

제가 이정표입니다. 
돈을 드릴수도 없고, 대가를 지불하지도 않습니다. 공정한 진술서를 미리 부탁 드리니까요.

황금률(=대우받고 싶은 데로 대접하라.)에 근거해서 요청합니다. 
공정하고 정확하 사실의 확인이며 본인의 양심에 따른 것을 원합니다.

저들은 4500만원을 제가 요구하고 4000으로 깎아서 제가 계약을 거부하였다.
제가 계약 파기 하였다고 주장하면서 소송하겠다고 주장했으니, 조금 불안합니다.

저를 고소하여도 여러분의 기억을 기록으로 남겨주시면
그들이 고소하면 진실을 밝히는 데 도움이 될 수 있지 겠습니까?

저는 여러분들을 만나면서 분명히 저희가 수령하는 돈은 3500이며 
그들에게 위임한 상태에서 나중에
파산하고 이혼한 사람에게 1000을 붙여서 4500을 받는 것을 묵과 할 수 없다고 
창녕경찰서와 농협 등 여러 군데 이야기 하고 호소하였습니다. 
특히 김미자씨를 만나려는 저의 의도는 정직하게 진실을 알리고 싶어서 입니다.
마지막에 4000만원으로 덮으려고 하고 복비도 안받는다 하여도 저는 참을 수가 없었습니다. 

사람이 과도하게 잘못된 거래를 눈감아 주면, 
결국 잘 알지 못하는 사람은 피해를 입는 나쁜 것에 동조하기 때문입니다.

그래서 저는 사과를 요구하였고 그들은 거짓말이라며 부인하였습니다.

제가 말하고 행한 것이 일관성이 있다면 향후 법정에 가는 경우에, 일관성있는 증거가 될 것이라고 생각합니다

저는 창녕경찰서 민원실 국민은행과 농협 콜센터 통화 녹음과 여러분들을 만나면서 말씀드린 사실을 증거로 맞서야 합니다.

그들이  소송하는 경우 저는 증거가 필요하므로 형사재판을 해야 할 것 같습니다.
여러분이 객관적인 기록을 남겨 주세요.

단 여러분이 직간접으로 보거나 알고 있는 사실입니다.
저는 먼저 소송할 생각이 현재는 없습니다. 요몇일새 이 문제로 골치가 아파도
양심에 가책으로 진행할 수 있었습니다. 
그래서 되도록 소송을 피하고 싶지만, 그렇기를 바라지만, 혹시 모르지요...
그들이 뻔뻔히 먼저 소송으로 나오면, 당당히 맞서야 할 것 같습니다.
그냥 일기장이나 서류함에 넣어 두시면 나중에 메모해 두시면서 혹시 저들이 소송걸면
향후 진술서의 초고가 될 자료를 사실대로 적어두시면 감사하겠습니다.
제가 한 말, 그리고 무슨 의도인 것 같은지, 
그리고 향후 제가 놓친 것이 무엇인지 
여러분이라면 어떻게 했을지 등등을 여러분의 솔직한 일기 남겨주세요.



저는 남이 억울하게 속는 것을 막고 싶었고 알려주고 싶었습니다.
제가 잘못했으면 제가 책임을 저야 합니다. 
여러분의 기록이 사람이 마음 놓고 믿고 살 수 있는 곳으로 만들어 가는 의지라고 생각합니다.
나중에 궁금한 사항이 있으시면 문자나 연락 주세요.
저의 연락처는 010-4897-6675 이정표 sunyta@yahoo.com sunyta2@naver.com







<핸드폰에 따른 시간표에 따른 것으로 추정되는 위치와 장소>

1588-2100 [2019-11-12 Tue 11:23] 농협 안에서 농협콜센타로 전화통화 05:30
1588-9999 [2019-11-12 Tue 11:29] 농협 안에서 국민은행으로 전화통화 08:46 동안 통화.
1588-9999 [2019-11-12 Tue 11:42] 국민은행콜센터에서 확인 전화통화 00:33 동안 통화.

010-9903-5555 [2019-11-12 Tue 12:59] 울산 부동산한곳과 통화시도함. 통화못함.
052-260-0040 [2019-11-12 Tue 13:05] 울산 부동산한곳과 통화시도함. 통화01:51.힐튼빌리지  주거상황문의
나무 부동산으로 추정됨. 상황설명함.
010-6801-0041 [2019-11-12 Tue 13:08] 울산 부동산한곳과 통화시도함. 통화04:35.힐튼빌리지  주거상황응답전화옴.


1588-9999 [2019-11-12 Tue 13:33] 국민은행콜센터에서 확인 다시 상황설명하고 전화통화 12:03 동안 통화.

010-2295-5544 [2019-11-12 Tue 13:58] 이정임과 통화 -강력항의하고 서류 발급하러 알아보러 읍사무소 들어감. 이후 통화거부함
자꾸 서류준비하라고 닥달함.
가난한 사람 이렇게 1000만원 갈취해도 돼냐고 따짐.
<이 때전화기 꺼놓음>

도저히 도의상 화가 나서 읍사무소에서 도장 등록부터 하라고 해서 집에 갔다가 
창녕경찰서로 간 것으로 추정됨.

010-2295-5544 [2019-11-12 Tue 14:55] 이정임의 메시지
매수인이 뒤땅을 살 필요 없답니다.
배짱부리는 양감님 협의 할 필요가 없습니다.
계약서에도 뒤땅5여평 물려있다고 고지 할 거구요.
010-2295-5544 [2019-11-12 Tue 15:06] 이정임의 메시지
사장님께서 뒤땅 얼마에 팔지 협의해 주시면 매수인에게 말해
보겠습니다.



창녕경찰서 민원실 방문해서 문의함. 사정 설명하고 협조 받을 수 있는지.
여직원 2분 있어서서 대화함.
결국 협조없어서 고민고민함. 어떻게 연락을 할 수 있을까?


010-2295-5544 [2019-11-13 Wed 10:37] 이정임과 통화거부  땅조아 공인중개사 이기영 055-533-1015
010-2295-5544 [2019-11-13 Wed 10:38] 이정임과 메시지
4000만원에 계약하기로 했습니다 (누구마음대로, 차라리 40억받아쳐먹고 사람 죽도록 하는 게 더 낳겠다.사기꾼들.)
사장님깨서 어려운 사람 조금만 받아라 해서요.
좋은 하루 되세요.(살살 똥꾸멍간질간질해서)

010-6536-3131 [2019-11-13 Wed 15:45] 목사님 부인의 메시지


[2019-11-13 Wed 16:07] 지구대 순찰대의 메시지를 남기는 부탁은 어떨까 해서 다시 도전해 보기 위해 창녕경찰서로 감.

182 [2019-11-13 Wed 16:07] 12:16 경찰 콜센터로 전화해서 사정이야기하고 울산 야음동지구대로 연결됨(녹음됬는지)
한분은  콜센터 남자분 이고 두번째는 야음동지구대 여자 순경에게 사정을 설명하고 도움을 요청함.
 
야음동이 부자 동네는 아니라는 창녕경찰서 민원실의 임신부 여자 순경의 설명을 듣게 됨.

결국 협조 실패함.



010-6536-3131 [2019-11-13 Wed 15:45] 목사님 부인의 전화통화 별이야기 없음.
010-9965-2742 [2019-11-13 Wed 17:31] 박동명 땅 경계 주인과 통화시도
055-532-2742 [2019-11-13 Wed 17:31] 박동명 땅 경계 주인과 통화 05:39 다음날 방문하라고 함.

055-532-2742 [2019-11-14 Thu 14:00] 박동명 땅 경계 주인과 통화 00:31 30분후 도착할 것으로 대합방문 약속함.

농협 들어가서 또한 번 문의함. 혹시 국민은행으로 직접가면 가능한지 자신이라면 가르쳐줄 수 있는 지 문의함.
울산을  직접못가면 밀양이나 다른 곳(대구)의 국민은행 가서 시도할 수 있을 지.

박하스 2박스 구입해서 방문.

골목길에 모여앉은 할머니 5분이 물어보길레 상황을 설명하고 분명히 3500만원이라고 이야기했음.

010-9965-2742 [2019-11-14 Thu 14:47] 박동명 땅 경계 주인과 만남.
박동명씨 내외 분과 분명히 이야기가 저희가 3500만원인데 중간에서 어르신 땅 해결도 못해 놓고 
4500만원으로 농간을 쳐서 직접왔다고 설명함.
없는 사람 1000만원 중간에 착곡하는 것을 그냥 방관할 수 없어서... 상의하러옴. 
만일 필요한 경우 계약의 당사자를 만날 의사는 있습니까? 만나기로 동의함

영감님을 만나고 악을 다시 선으로 변환하는 능력의 발굴! 
 138-4 138-5 우리땅
136 영감님 땅 180평 400평
자본주의의 능력을 올바르게 탐욕을 동력으로 진격.


아버지와 통화 [2019-11-14 Thu 16:21] 07:57


010-2295-5544 [2019-11-15 Fri 09:53] 이정임의 메시지
010-2295-5544 [2019-11-15 Fri 10:54] 이정임의 전화 거부함
010-2295-5544 [2019-11-15 Fri 10:57] 이정임의 메시지
010-2295-5544 [2019-11-15 Fri 15:11] 이정임의 전화 거부함


010-2295-5544 [2019-11-16 Sat 15:11] 이정임의 전화 거부함
[2019-11-16 Sat 15:11] 땅조아 공인중개사 이기영 055-533-1015
드디어 만남 김미자씨 남편 와있었음
대화 결렬. 이사람들 사기치려한 것을 밝힘. 그래두 무심한 반응. 그래서 어떻할 것이냐고 함.
사과하라고 요구함. 핑계대면서 사람을 빼돌림.
아버지와 계약금 반환요구를 들어서 시행하라고 함.

입금하고 와라고 하면서 놀리면서 
공휴일이라서 그리고 통장 라인이 2줄뿐이라서 입력이 안됨.
돈도 없이 계약해지는 안된다고 함. 그래서 월요일입금안되냐니까 거부함.

이정임이라는 여자의 헛웃음 


인터넷 송금액을 제한 한 것을 뒤듯게 발견한 것이 문제. 그리고 통장페이지 공란이 2줄만 남음.
자기네들이 빌려줄 것같이 신분증 복사하더니 못믿는다면서 현금갖고 오라고 함. =>이래서 평일날 거래해야 함.

[2019-11-16 Sat 17:00] 여러 사람들한테 연락함. 목사님 사모님께 과 통화하고  현금 400만원 빌리는 데 연락함.
시장통안 농협에서 출금하고 


운전해서 부동산 사무실로 옴
400만원 당당히 반환함.
나의 계약 위반이라면서 부동산의 쪽에서 400만원을 요구할 것을 물어 봄.
은인의 등을 치려는 자의 어리석음. 깊은 수렁의 느낌. 계약위반으로 800만원이 아니냐는 식.

[2019-11-16 Sat 17:31] 박동명씨 전화와서 만날 의사 물어보니 나중에 오라고 함.


거짓말 논쟁으로 일관된 부인 작전과 이전에 군말 없던 계약 위반 운운하며 고소할 거라며 나가라고 밀침.
길거리로 밀려나와서 씩씩거리며 차로 돌아감.

[2019-11-16 Sat 17:40] 너무 화가 나서, 무쏘 차량 후진하면서 가로등에 부딫혀서 뒤의 범퍼 찌그러짐
나의 과실 그러나 정말 화가 나서 경황도 없었음.


[2019-11-16 Sat 17:53] 목사님 부인께 감사의 통화를 함. 감사의 문자를 보냄.


[2019-11-16 Sat 20:06] 메시지로 사과를 요구함.


[2019-11-16 Sat 20:09] 메시지로 사과를 요구함.
이정임씨 하늘이 알고 당신 양심이 알고 있을 겁니다
천벌이 두려워서라도 거짓말 않아야 삽니다!
뻔뻔한 거짓으로 망합니다! 반성하시요! 하늘에 호소합니다!
[2019-11-16 Sat 20:10] 이정임의 메시지
당신집은
창녕에서는 못팔겁니다
인생그리 살지 마세요

[2019-11-16 Sat 20:18] 메시지로 사과를 요구함.
거짓과  고소협박으로 진실을 가릴수는 없지요! 나무 지장보살
[2019-11-16 Sat 20:12] 이정임의 메시지
다시 연락하지 마세요.
[2019-11-16 Sat 20:14] 이정임의 메시지
사장님 아들이 위약금 청구하겠다고 연락이 왔슴다
[2019-11-16 Sat 20:26] 이정임의 메시지
옳지도 않은 팔려고 그렇게 친절하더니 계약하고나니
뒤통수치는 사람으로 모두가 알게 될 겁니다.

[2019-11-16 Sat 20:28] 메시지로 사과를 요구함.
창녕경찰서 민원실 농협국민은행 고객통화녹음있을 테니 이렇게 무슨 거짓이 있겠소

[2019-11-16 Sat 20:30] 이정임의 메시지
상대하기 싫으니 그만 하소.

[2019-11-16 Sat 20:32] 메시지로 사과를 요구함.
이정임씨 경찰증인 증거 충분히 녹음있을 겁니다
반성하고 사과하시요.

[2019-11-16 Sat 20:36] 이정임의 메시지
자꾸 이러면 신고 합니다
그만 하시오.

인간에 대한 깊은 환멸감. 이민가고 싶다는 충동을 느낌.
* [2019-11-19 Tue 13:56] 컴퓨터의 실행이 가동되는 거세 감탄함.
범주와 타입은 동일한 것이다.
function application == function calling
f:a -> a
g:a -> a
(f g) = h:a -> a
function composition function compositionality
composability
동일타입을 생성함=동일타입을 합쳐서 만들어진 것 마노이드의 핵심개념

복잡성의 증가에서 확장으로 인한 통제불능 => 복잡성의 통제가 절실히 요구됨.
작은 조각을 구성해서 디자인으로 스스로 만들어서 조립하는 것이 복잡성을 감소시킴.
작은 빌딩블록에서 출발하는 것이 현명하다.
일반적인 합성연산자를 만들어서 시작함.

Monoid: 물건의 집합과 조립의 룰을 합친 것 그 규칙은 상위 규칙을 준수함.
상위룰 중에
a(bc)=(ab)c asociative rule
x+12=x unit의 존재함.
xy/=/yz

a => ........ C#
\a -> 

=====================
g:a->b
f:b->c
(f.g):a->c
(f.g)a = f(ga)
--------------
g:a->Mb
f:b->Mc
\a-> [ (ga) >>= \b -> (fb) ]
       Mb -> ((b->Mc) -> Mc

myList = ["a"] --"a":[]
myFunc :: (Num a, Enum a) => [b] -> int -> [(a,b)]
myFunc (x:xs) n = foldr (\i acc -> (i,x):acc) [] (take n [1..]) #https://youtu.be/MlZCiiKGbb0?t=456
-- foldr :: (a -> b ->b} -> b -> [a] -> b

myFunc myList 3 = 1:2:3:[]
syntactic sugar

* 재물에 눈이 있다는 사실이다.
100년동안 묵어있던 일제이름으로 등록된 문중의 재산이 빠진 것으로 쉽게 보면 큰일 난다.


* #+OPTIONS: toc:nil 
#+STARTUP: hidestars indent inlineimages

# YouTube : https://youtu.be/cPZe0AGOUJU?t=323
* #+BEGIN_SRC ditaa :file ditaa.png
#+BEGIN_SRC ditaa :file ditaa.png

+----+      /--------\
|    |      |        |
|zed +----->+  two   |
|{d} |      |        |
+----+      \--------/
#+END_SRC


#+BEGIN_SRC dot :file dot.png
graph G {
zed--b;
a--c;
c--d;
}
#+END_SRC

* [2019-11-24 Sun]
* 사백만원 반환 영수증

2019년 11월 06일 오후 2시 경에 
국민은행(예금주:김미자): 96300201299304 로부터
농협(예금주:이정표): 352-0036-7735-23 으로
계좌 이체된 사백만원을

2019년 11월 16일 토요일 오후 5시 경에
창녕읍 내 땅조아 공인중개사 사무실 안에서
이정표가 성인기에게 
오만원권 팔십매로 현금 사백만원을 정확히 반환하였습니다.
그리고 김미자는 성인기로부터의 사백만원 수령을 확인하였습니다.

위 사항에 대하여 금융거래 내역을 명확히 하고자 이 영수증을 작성합니다.


반환인: 이정표 010-4897-6675

전달자:
 
수령인:

2019년 11월 24일 경남 창녕군 대합면 신당리
