

* C-t fn_F11 full
- C-t M-tab (원하는 2창을 서로 호환함) 스텀프의 굉장한 장점임!!! 고정을 정확하게 하면 유튜브 시청에 효용이 극대화된다.
어썸윈도우 메니져가 불필요함.

(dump-group-to-file "/home/thinkpad/config_github/app/stumpwm/full_screen_stumpwm_workflow.org.cl")
(dump-group-to-file "/home/thinkpad/config_github/app/stumpwm/full_screen_stumpwm_workflow.org1_.cl")
(dump-group-to-file "/home/thinkpad/config_github/app/stumpwm/full_screen_stumpwm_workflow.org2_.cl")
(dump-group-to-file "/home/thinkpad/config_github/app/stumpwm/full_screen_stumpwm_workflow.org3_.cl")

restore-from-file "/home/thinkpad/config_github/app/stumpwm/full_screen_stumpwm_workflow.org.cl")
(restore-from-file "~/config_github/app/stumpwm/full_screen_stumpwm_workflow.org1_third_edit.cl")
~/config_github/app/stumpwm/full_screen_stumpwm_workflow.org1_second_edit_number.cl")



(restore-from-file "~/config_github/app/stumpwm/layout1_edit_back.cl")
~/config_github/app/stumpwm/layout1_edit.cl")

(dump-group-to-file "~
(restore-from-file "~/config_github/app/stumpwm/LAYOUT/LAYOUT2.el")
(restore-from-file "~/config_github/app/stumpwm/LAYOUT/LAYOUT3.el")
* C-t C-화살표 를 이동하면서 표현하는 것으로 정하여 쉽게 사용하도록한다.

** 다른 것으로 이동하는 것을 고려할 것

Barba non facit philosophum
A beard does not make a philosopher

Barba non facit philosophum
A beard does not make a philosopher

Barba non facit philosophum
A beard does not make a philosopher


* m을 프리픽스로 고치고, 정확히 이동하는 것을 아래에 배치한다.
옮기는 것을 직관적으로 고친다.


* 규칙을 새로만들고 그규칙을 현재 그룹에만 적용하는 것이 
- 많은 규칙을 간이하게 만드는 메타사고와 수행이 요구된다.
